function syncFreeGameCopy(){T.zh.gameSub=adminSettings.freeGames?`${arcadeGameCount} 款独立小游戏 · 管理员已开启免积分游玩`:`${arcadeGameCount} 款独立小游戏 · 兑换时间后畅玩`;T.en.gameSub=adminSettings.freeGames?`${arcadeGameCount} independent games · Free play enabled by administrator`:`${arcadeGameCount} independent games · Redeem time to play`;if(typeof gameEntrySub!=='undefined')gameEntrySub.textContent=T[lang].gameSub}
function loadAdminSettings(){try{const saved=JSON.parse(localStorage.getItem(ADMIN_SETTINGS_KEY)||'{}'),cap=Math.floor(Number(saved.pointCap)),minutes=Math.floor(Number(saved.gameMinutesCap)),allowed=saved.allowedLevels||{};adminSettings.pointCap=Number.isFinite(cap)&&cap>=0?Math.min(cap,999999999):DEFAULT_POINT_CAP;adminSettings.freeGames=saved.freeGames===true;adminSettings.gameMinutesCap=[5,10,15,20,30,45,60].includes(minutes)?minutes:DEFAULT_GAME_MINUTES;adminSettings.allowedLevels={math:Array.isArray(allowed.math)?allowed.math.map(String):[],english:Array.isArray(allowed.english)?allowed.english.map(String):[],science:Array.isArray(allowed.science)?allowed.science.map(String):[]}}catch{adminSettings={pointCap:DEFAULT_POINT_CAP,freeGames:false,gameMinutesCap:DEFAULT_GAME_MINUTES,allowedLevels:{math:[],english:[],science:[]}}}syncFreeGameCopy()}
function saveAdminSettings(){localStorage.setItem(ADMIN_SETTINGS_KEY,JSON.stringify(adminSettings))}
function allowedLevelIds(subjectId){const configured=adminSettings.allowedLevels?.[subjectId]||[];return configured.length?new Set(configured.map(String)):null}
function renderAdminLevels(){if(!banks.math||!banks.english||!banks.science){adminLevelGroups.innerHTML=`<div style="color:#8297b3">${lang==='zh'?'题库加载中…':'Loading question banks…'}</div>`;return}const names={math:lang==='zh'?'数学':'Math',english:'English',science:lang==='zh'?'科学':'Science'};adminLevelGroups.innerHTML=['math','english','science'].map(subjectId=>{const allowed=allowedLevelIds(subjectId),levelsForSubject=banks[subjectId].levels;return `<details class="admin-level-group" open><summary>${names[subjectId]} · ${allowed?allowed.size:levelsForSubject.length}/${levelsForSubject.length}</summary><div class="admin-level-actions"><button type="button" onclick="toggleAdminLevels('${subjectId}',true)">${lang==='zh'?'全选':'Select all'}</button><button type="button" onclick="toggleAdminLevels('${subjectId}',false)">${lang==='zh'?'清空':'Clear'}</button></div><div class="admin-level-options">${levelsForSubject.map(level=>`<label class="admin-level-option"><input type="checkbox" data-admin-level="${subjectId}" value="${esc(level.id)}" ${!allowed||allowed.has(String(level.id))?'checked':''}><span>${esc(tx(level.name))}</span></label>`).join('')}</div></details>`}).join('')}
function toggleAdminLevels(subjectId,checked){document.querySelectorAll(`[data-admin-level="${subjectId}"]`).forEach(input=>input.checked=checked)}
async function hashSecret(value){const raw=String(value);if(crypto?.subtle){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('')}let h=2166136261;for(const ch of raw){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return `fallback-${h>>>0}`}
async function verifyAdminPassword(value){const stored=localStorage.getItem('wuming_admin_password_hash_v1'),candidate=await hashSecret(value);return candidate===(stored||await hashSecret('0000'))}
function applyAdminMode(){document.body.classList.toggle('admin-mode',adminActive);adminEntry.classList.toggle('active',adminActive);adminEntry.setAttribute('aria-pressed',String(adminActive));adminBadge.textContent=lang==='zh'?'管理员':'ADMIN';adminEntry.textContent=adminActive?(lang==='zh'?'⚙ 管理中':'⚙ ADMIN'):(lang==='zh'?'⚙ 管理':'⚙ Admin')}
function setAdminMessage(text='',ok=false){const box=document.getElementById('adminMessage');box.textContent=text;box.className=`admin-message${ok?' ok':''}`}
function openAdmin(){setAdminMessage('');adminPassword.value='';oldPassword.value='';newPassword.value='';passwordChangeForm.hidden=true;adminExitForm.hidden=true;adminLoginView.hidden=adminActive;adminConsoleView.hidden=!adminActive;if(adminActive){adminPointsInput.value=user.points;adminCapInput.value=adminSettings.pointCap;adminGameMinutesCap.value=adminSettings.gameMinutesCap;adminFreeGames.checked=adminSettings.freeGames;renderAdminLevels()}translateAdmin();adminModal.hidden=false;document.body.style.overflow='hidden';setTimeout(()=>adminActive?adminPointsInput.focus():adminPassword.focus(),0)}
function closeAdmin(){adminModal.hidden=true;document.body.style.overflow='';setAdminMessage('')}
async function loginAdmin(event){event.preventDefault();if(!await verifyAdminPassword(adminPassword.value)){setAdminMessage(lang==='zh'?'密令错误。':'Incorrect passcode.');adminPassword.select();return}adminActive=true;sessionStorage.setItem(ADMIN_ACTIVE_KEY,'true');translateAdmin();adminLoginView.hidden=true;adminConsoleView.hidden=false;adminPointsInput.value=user.points;adminCapInput.value=adminSettings.pointCap;adminGameMinutesCap.value=adminSettings.gameMinutesCap;adminFreeGames.checked=adminSettings.freeGames;renderAdminLevels();setAdminMessage(lang==='zh'?'管理员模式已开启。':'Administrator mode enabled.',true)}
function saveAdminValues(){const points=Math.floor(Number(adminPointsInput.value)),cap=Math.floor(Number(adminCapInput.value)),minutes=Math.floor(Number(adminGameMinutesCap.value));if(!Number.isFinite(points)||points<0||!Number.isFinite(cap)||cap<0||points>999999999||cap>999999999||![5,10,15,20,30,45,60].includes(minutes)){setAdminMessage(lang==='zh'?'请检查积分与游戏时间上限。':'Check the point and game-time limits.');return}const nextAllowed={};for(const subjectId of ['math','english','science']){nextAllowed[subjectId]=[...document.querySelectorAll(`[data-admin-level="${subjectId}"]:checked`)].map(input=>input.value);if(!nextAllowed[subjectId].length){setAdminMessage(lang==='zh'?`请至少保留一个${subjectId==='math'?'数学':subjectId==='science'?'科学':'英语'}等级。`:`Keep at least one ${subjectId} level.`);return}}adminSettings.pointCap=cap;adminSettings.gameMinutesCap=minutes;adminSettings.freeGames=adminFreeGames.checked;adminSettings.allowedLevels=nextAllowed;user.points=Math.min(points,cap);saveAdminSettings();saveUser();syncFreeGameCopy();updateDash();adminPointsInput.value=user.points;adminCapInput.value=cap;if(subject!=='none')populate();renderAdminLevels();setAdminMessage(lang==='zh'?`管理设置已保存；单次游戏时间上限为 ${minutes} 分钟。`:`Admin settings saved. The per-session game limit is ${minutes} minutes.`,true)}
function showAdminExit(){adminExitForm.hidden=false;adminExitPassword.value='';setAdminMessage('');adminExitPassword.focus()}
async function logoutAdmin(event){event.preventDefault();if(!await verifyAdminPassword(adminExitPassword.value)){setAdminMessage(lang==='zh'?'密令错误，管理员模式仍保持开启。':'Incorrect passcode. Administrator mode remains active.');adminExitPassword.select();return}adminActive=false;sessionStorage.removeItem(ADMIN_ACTIVE_KEY);applyAdminMode();closeAdmin()}
function togglePasswordChange(){passwordChangeForm.hidden=!passwordChangeForm.hidden;setAdminMessage('');if(!passwordChangeForm.hidden){oldPassword.value='';newPassword.value='';oldPassword.focus()}}
async function changeAdminPassword(event){event.preventDefault();if(!await verifyAdminPassword(oldPassword.value)){setAdminMessage(lang==='zh'?'旧密码不正确。':'The old password is incorrect.');oldPassword.select();return}if(newPassword.value.length<4){setAdminMessage(lang==='zh'?'新密码至少需要 4 位。':'The new password must contain at least 4 characters.');return}localStorage.setItem('wuming_admin_password_hash_v1',await hashSecret(newPassword.value));passwordChangeForm.reset();passwordChangeForm.hidden=true;setAdminMessage(lang==='zh'?'管理员密码已更改。':'Administrator password changed.',true)}
function translateAdmin(){const zhMode=lang==='zh';adminTitle.textContent=adminActive?(zhMode?'管理员控制台':'Administrator Console'):(zhMode?'管理员验证':'Administrator Verification');adminCopy.textContent=adminActive?(zhMode?'可设置积分、游戏权限和孩子能够练习的题目等级。':'Set points, game access, and exactly which question levels the child may practice.'):(zhMode?'输入管理员密令以启用管理模式。':'Enter the administrator passcode to enable administrator mode.');adminPasswordLabel.textContent=zhMode?'管理员密令':'Administrator passcode';adminLoginButton.textContent=zhMode?'进入管理员模式':'Enter Administrator Mode';adminPointsLabel.textContent=zhMode?'当前积分':'Current points';adminCapLabel.textContent=zhMode?'积分上限':'Point cap';adminGameMinutesLabel.textContent=zhMode?'游戏时间兑换上限':'Game-time redemption limit';[...adminGameMinutesCap.options].forEach(option=>option.textContent=zhMode?`${option.value} 分钟`:`${option.value} minutes`);adminFreeGamesTitle.textContent=zhMode?'游戏免积分':'Free game access';adminFreeGamesCopy.textContent=zhMode?'开启后无需积分即可进入游戏；退出管理员模式后仍保持生效，直到手动关闭。':'Play without points. This remains enabled after leaving admin mode until manually switched off.';adminLevelTitle.textContent=zhMode?'允许练习的等级':'Allowed question levels';adminLevelCopy.textContent=zhMode?'可按学科多选；孩子只会看到已勾选的等级。':'Select multiple levels per subject. Only checked levels remain visible.';adminSaveButton.textContent=zhMode?'保存管理设置':'Save Admin Settings';adminActiveText.textContent=zhMode?'● 管理员模式已开启':'● Administrator mode enabled';adminExitButton.textContent=zhMode?'退出管理员模式':'Exit Administrator Mode';adminExitPasswordLabel.textContent=zhMode?'重新输入密令以关闭':'Re-enter passcode to disable';adminExitConfirm.textContent=zhMode?'验证并关闭':'Verify & Disable';passwordIconText.textContent=zhMode?'更改密码':'Change Password';oldPasswordLabel.textContent=zhMode?'旧密码':'Old password';newPasswordLabel.textContent=zhMode?'新密码':'New password';changePasswordButton.textContent=zhMode?'确认更改':'Confirm Change';if(adminActive&&!adminConsoleView.hidden)renderAdminLevels();applyAdminMode()}
