const GAME_SESSION_KEY='gongxing_arcade_session_v1',GAME_POINT_COST=5;let redemptionInProgress=false;
function freeGameMode(){return adminSettings.freeGames===true}
function gameMinuteCap(){return Math.max(1,Math.min(MAX_GAME_MINUTES,Number(adminSettings.gameMinutesCap)||DEFAULT_GAME_MINUTES))}
function readGameSession(){try{const s=JSON.parse(localStorage.getItem(GAME_SESSION_KEY)||'null'),now=Date.now(),validCost=s?.free===true?freeGameMode()&&s.cost===0:s?.cost===s?.minutes*GAME_POINT_COST;if(!s||!Number.isInteger(s.minutes)||s.minutes<1||s.minutes>MAX_GAME_MINUTES||!validCost){if(s?.free===true)localStorage.removeItem(GAME_SESSION_KEY);return null}const total=s.minutes*60000,remaining=s.version===1&&Number.isFinite(s.expiresAt)?s.expiresAt-now:s.version===2&&Number.isFinite(s.remainingMs)?s.remainingMs-(Number.isFinite(s.activeSince)?Math.max(0,now-s.activeSince):0):0;if(remaining<=0||remaining>total+1500)return null;const paused={...s,version:2,remainingMs:Math.min(total,remaining),activeSince:null,expiresAt:null};localStorage.setItem(GAME_SESSION_KEY,JSON.stringify(paused));return paused}catch{return null}}
function formatGameTime(ms){const seconds=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(seconds/60),s=seconds%60;return `${m}:${String(s).padStart(2,'0')}`}
function refreshPointBalance(){try{const latest=JSON.parse(localStorage.getItem('gongxing_academy_data')||'{}');if(Number.isFinite(Number(latest.points)))user.points=Math.min(adminSettings.pointCap,Math.max(0,Math.floor(Number(latest.points))))}catch{}if(typeof gamePointBalance!=='undefined')gamePointBalance.textContent=user.points}
function openExchange(){refreshPointBalance();renderExchange();exchangeModal.hidden=false;document.body.style.overflow='hidden'}
function closeExchange(){exchangeModal.hidden=true;document.body.style.overflow=''}
function renderExchange(){
  refreshPointBalance();const zhMode=lang==='zh',session=readGameSession(),free=freeGameMode(),cap=gameMinuteCap();
  exchangeTitle.textContent=free?(zhMode?'免积分进入游戏':'Free Game Access'):(zhMode?'兑换游戏时间':'Redeem Game Time');exchangeCopy.textContent=free?(zhMode?`管理员已开启游戏免积分模式，无需消耗学习积分。每次进入可游玩 ${cap} 分钟。`:`The administrator enabled free game access. Each entry grants ${cap} minutes without points.`):(zhMode?`每 5 积分可兑换 1 分钟，本次最多兑换 ${cap} 分钟。`:`Redeem 1 minute for every 5 points, up to ${cap} minutes per session.`);exchangeBalanceLabel.textContent=zhMode?'当前积分':'Point balance';exchangePointUnit.textContent=zhMode?'积分':'points';exchangeMinutesLabel.textContent=zhMode?'兑换时长':'Play time';exchangeCostUnit.textContent=zhMode?'积分':'points';exchangeAction.textContent=free?(zhMode?'免费进入游戏':'Enter Arcade Free'):(zhMode?'兑换并进入游戏':'Redeem & Enter Arcade');exchangeNote.textContent=free?(zhMode?'免积分选项会持续生效，只有管理员手动关闭后才恢复积分兑换。':'Free play stays active until an administrator manually disables it.'):(zhMode?'答对 1 题获得 1 积分；5 题全对额外奖励 1 积分。倒计时结束后将自动返回刷题页面。':'Earn 1 point per correct answer, plus 1 bonus point for a perfect 5/5. When time expires, you will return to the learning page.');exchangePoints.textContent=user.points;
  if(session){exchangePurchase.hidden=true;exchangeActive.hidden=false;exchangeActive.innerHTML=`${zhMode?'已暂停的游戏时间：':'Paused play time: '}<strong>${formatGameTime(session.remainingMs)}</strong><br><button class="exchange-action" style="margin-top:12px" onclick="location.href='games.html'">${zhMode?'继续游戏':'Continue Playing'}</button>`;return}
  exchangePurchase.hidden=false;exchangeActive.hidden=true;exchangePicker.hidden=free;if(free){exchangeAction.disabled=false;return}const max=Math.min(cap,Math.floor(user.points/GAME_POINT_COST));exchangeMinutes.innerHTML=max?Array.from({length:max},(_,i)=>`<option value="${i+1}">${i+1} ${zhMode?'分钟':i===0?'minute':'minutes'}</option>`).join(''):`<option value="0">${zhMode?'积分不足':'Not enough points'}</option>`;exchangeAction.disabled=max===0;updateExchangeCost()
}
function updateExchangeCost(){exchangeCost.textContent=(Number(exchangeMinutes.value)||0)*GAME_POINT_COST}
async function redeemGameTime(){
  if(redemptionInProgress)return;redemptionInProgress=true;exchangeAction.disabled=true;
  const perform=()=>{if(readGameSession()){location.href='games.html';return}const now=Date.now(),cap=gameMinuteCap();if(freeGameMode()){const minutes=cap;localStorage.setItem(GAME_SESSION_KEY,JSON.stringify({version:2,issuedAt:now,remainingMs:minutes*60000,activeSince:null,expiresAt:null,minutes,cost:0,free:true,nonce:crypto.randomUUID?.()||String(now)+Math.random()}));location.href='games.html';return}const minutes=Number(exchangeMinutes.value);if(!Number.isInteger(minutes)||minutes<1||minutes>cap){redemptionInProgress=false;renderExchange();return}const cost=minutes*GAME_POINT_COST;let latest;try{latest=JSON.parse(localStorage.getItem('gongxing_academy_data')||'{}')}catch{redemptionInProgress=false;renderExchange();return}const balance=Math.max(0,Math.floor(Number(latest.points)||0));if(balance<cost){user.points=balance;redemptionInProgress=false;renderExchange();return}latest.points=balance-cost;localStorage.setItem('gongxing_academy_data',JSON.stringify(latest));user.points=latest.points;localStorage.setItem(GAME_SESSION_KEY,JSON.stringify({version:2,issuedAt:now,remainingMs:minutes*60000,activeSince:null,expiresAt:null,minutes,cost,free:false,nonce:crypto.randomUUID?.()||String(now)+Math.random()}));location.href='games.html'};
  if(navigator.locks)await navigator.locks.request('gongxing-points',perform);else perform()
}
