function loadUser(){try{const s=localStorage.getItem('gongxing_academy_data');if(s){const saved=JSON.parse(s);user={...user,...saved,mastery:{...user.mastery,...(saved.mastery||{})},wrongBook:saved.wrongBook||[],unlockedAchievements:saved.unlockedAchievements||[]};user.points=Number.isFinite(Number(saved.points))?Math.min(adminSettings.pointCap,Math.max(0,Math.floor(Number(saved.points)))):0}}catch{}const todayDate=new Date().toLocaleDateString(),y=new Date();y.setDate(y.getDate()-1);if(user.lastDate!==todayDate){if(user.lastDate&&user.lastDate!==y.toLocaleDateString())user.streak=0;user.todaySolved=0}updateDash()}
function saveUser(){localStorage.setItem('gongxing_academy_data',JSON.stringify(user))}
function updateDash(){today.textContent=user.todaySolved;accuracy.textContent=(user.totalSolved?Math.round(user.totalCorrect/user.totalSolved*100):0)+'%';streak.textContent=user.streak;if(typeof pointsStat!=='undefined')pointsStat.textContent=user.points;if(typeof gamePointBalance!=='undefined')gamePointBalance.textContent=user.points;unlockAchievements();renderAchievements()}
function unlockAchievements(){let changed=false;for(const achievement of ACHIEVEMENTS){if(achievement.test(user)&&!user.unlockedAchievements.includes(achievement.id)){user.unlockedAchievements.push(achievement.id);changed=true}}if(changed)saveUser()}
function achievementText(achievement,key){return lang==='zh'?achievement[key]:achievement[key==='zh'?'en':'enDesc']}
function renderAchievements(){const unlocked=new Set(user.unlockedAchievements),equipped=ACHIEVEMENTS.find(a=>a.id===user.equippedTitle&&unlocked.has(a.id));equippedTitle.hidden=!equipped;equippedTitle.textContent=equipped?`${equipped.icon} ${lang==='zh'?'已装备：':'Equipped: '}${lang==='zh'?equipped.zh:equipped.en}`:'';badges.innerHTML=`<span class="badge gold">🏆 ${lang==='zh'?'已解锁':'Unlocked'} ${unlocked.size}/${ACHIEVEMENTS.length}</span>`;achievementKicker.textContent=T[lang].titlesKicker;achievementHeading.textContent=T[lang].titles;achievementSummary.textContent=lang==='zh'?`点击已解锁的成就即可装备称号（${unlocked.size}/${ACHIEVEMENTS.length}）`:`Select an unlocked achievement to equip its title (${unlocked.size}/${ACHIEVEMENTS.length})`;achievementGrid.innerHTML=ACHIEVEMENTS.map(a=>{const isUnlocked=unlocked.has(a.id),isEquipped=user.equippedTitle===a.id;return `<button class="achievement-card ${isUnlocked?'':'locked'} ${isEquipped?'equipped':''}" onclick="equipAchievement('${a.id}')" ${isUnlocked?'':'disabled'}><span class="achievement-icon">${isUnlocked?a.icon:'🔒'}</span><span class="achievement-copy"><span class="achievement-name">${esc(lang==='zh'?a.zh:a.en)}</span><span class="achievement-desc">${esc(lang==='zh'?a.zhDesc:a.enDesc)}</span><span class="achievement-state">${isEquipped?(lang==='zh'?'已装备':'Equipped'):isUnlocked?(lang==='zh'?'点击装备':'Click to equip'):(lang==='zh'?'尚未解锁':'Locked')}</span></span></button>`}).join('')}
function equipAchievement(id){if(!user.unlockedAchievements.includes(id))return;user.equippedTitle=user.equippedTitle===id?'':id;saveUser();renderAchievements()}
function toggleAchievements(){const panel=document.getElementById('achievementPanel'),chevron=document.getElementById('achievementChevron');panel.hidden=!panel.hidden;chevron.textContent=panel.hidden?'▾':'▴';if(!panel.hidden)panel.scrollIntoView({block:'nearest',behavior:'smooth'})}
function setLang(l){if(subject==='english'&&l!=='en')return;lang=l;localStorage.setItem('gongxing_lang',l);document.documentElement.lang=l==='zh'?'zh-CN':'en';document.title=T[l].pageTitle;document.querySelector('.brand').dataset.logo=T[l].logo;brandName.textContent=T[l].brand;en.textContent=l==='zh'?'英文':'EN';en.className=l==='en'?'active':'';zh.textContent=l==='zh'?'中文':'ZH';zh.className=l==='zh'?'active':'';heroKicker.textContent=T[l].heroKicker;heroTitle.textContent=T[l].heroTitle;heroEm.textContent=T[l].heroEm;heroCopy.textContent=T[l].heroCopy;heroTagReady.textContent=T[l].heroReady;heroTagRound.textContent=T[l].heroRound;heroTagSubjects.textContent=T[l].heroSubjects;heroMap.dataset.steps=T[l].heroSteps;homeTitle.textContent=T[l].home;homeSubtitle.textContent=T[l].sub;mathTitle.textContent=T[l].math;englishTitle.textContent=T[l].english;scienceTitle.textContent=T[l].science;mathDesc.textContent=T[l].mathDesc;englishDesc.textContent=T[l].englishDesc;scienceDesc.textContent=T[l].scienceDesc;mathCard.dataset.action=T[l].cardAction;englishCard.dataset.action=T[l].cardAction;scienceCard.dataset.action=T[l].cardAction;start.textContent=T[l].start;prev.textContent=T[l].prev;next.textContent=T[l].next;submit.textContent=T[l].submit;todayLabel.textContent=T[l].today;accuracyLabel.textContent=T[l].accuracy;streakLabel.textContent=T[l].streak;pointsLabel.textContent=T[l].points;setupNote.textContent=T[l].note;if(typeof hardModeText!=='undefined')hardModeText.textContent=hardMode?(l==='zh'?'困难 · 开启':'HARD · ON'):(l==='zh'?'困难':'HARD');if(typeof gameEntryTitle!=='undefined'){gameEntryTitle.textContent=T[l].game;gameEntrySub.textContent=T[l].gameSub;gamePointUnit.textContent=T[l].pointUnit}if(typeof usageEntryTitle!=='undefined'){usageEntryTitle.textContent=T[l].usageTitle;usageEntrySub.textContent=T[l].usageSub}translateAdmin();if(!exchangeModal.hidden)renderExchange();if(!usageModal.hidden)renderUsage();if(subject!=='none'){crumb.textContent='> '+T[l][subject];populate()}if(questions.length)render();renderAchievements()}

function toggleHardMode(){hardMode=!hardMode;document.body.classList.toggle('hard-mode',hardMode);hardModeToggle.classList.toggle('is-on',hardMode);hardModeToggle.setAttribute('aria-pressed',String(hardMode));hardModeText.textContent=hardMode?(lang==='zh'?'困难 · 开启':'HARD · ON'):(lang==='zh'?'困难':'HARD');setupNote.textContent=hardMode?(lang==='zh'?'困难模式：竞赛难度 · 5 题 · 红色警戒':'HARD mode: contest difficulty · 5 questions · red alert'):T[lang].note}
function makeHardQuestion(id,type,zh,en,answer,knowledge,options){return{id,type,question:{zh,en},answer,knowledge,difficulty:5,...(options?{options:options.map(x=>({zh:x,en:x}))}:{})}}
function hardModeQuestions(level){const n=Number(level.id),p='hard_'+subject+'_'+n+'_';if(subject==='math'){if(n<4)return[makeHardQuestion(p+'1','number','计算：48 × 7 - 36 ÷ 4 + 19 = ?','Calculate 48 × 7 - 36 ÷ 4 + 19.',346,'多步运算'),makeHardQuestion(p+'2','number','长方形长 17 cm、宽 9 cm，面积与周长的和是多少？','A rectangle is 17 cm by 9 cm. Find area plus perimeter.',205,'几何综合'),makeHardQuestion(p+'3','number','有 18 盒，每盒 14 支笔，送出 37 支后还剩多少支？','18 boxes hold 14 pens each. After giving away 37, how many remain?',215,'应用题'),makeHardQuestion(p+'4','number','125 - 38 + 46 - 29 = ?','Calculate 125 - 38 + 46 - 29.',104,'数感'),makeHardQuestion(p+'5','number','27 × 8 - 19 × 6 = ?','Calculate 27 × 8 - 19 × 6.',102,'乘法综合')];if(n<7)return[makeHardQuestion(p+'1','number','解方程：7x - 19 = 156，x = ?','Solve 7x - 19 = 156.',25,'方程'),makeHardQuestion(p+'2','number','3/8 + 5/12 = ?（输入小数）','3/8 + 5/12 = ? (decimal)',19/24,'分数'),makeHardQuestion(p+'3','number','原价 250 元，先涨价 20% 再打八折，现价多少元？','A 250-yuan item rises 20%, then gets 20% off.',240,'百分数'),makeHardQuestion(p+'4','number','半径为 7 cm 的圆，取 π=3.14，面积是多少？','A circle has radius 7; use π=3.14.',153.86,'圆'),makeHardQuestion(p+'5','number','速度 54 km/h，行驶 2.5 小时后再行驶 18 km，总路程多少 km？','Travel 54 km/h for 2.5 h, then 18 km more.',153,'行程')];if(n<10)return[makeHardQuestion(p+'1','number','解方程：8(x - 3) = 136，x = ?','Solve 8(x - 3) = 136.',20,'代数'),makeHardQuestion(p+'2','number','函数 y = 4x² - 11，当 x=3 时，y=?','For y=4x²-11, find y at x=3.',25,'函数'),makeHardQuestion(p+'3','number','直角三角形两直角边为 9 和 12，斜边长度的平方是多少？','A right triangle has legs 9 and 12. What is c²?',225,'几何'),makeHardQuestion(p+'4','number','数据 7、10、13、16、19 的平均数是多少？','Find the mean of 7, 10, 13, 16, 19.',13,'统计'),makeHardQuestion(p+'5','number','计算：-24 + 17 × 4 - 13 = ?','Calculate -24 + 17 × 4 - 13.',31,'有理数')];return[makeHardQuestion(p+'1','number','f(x) = 3x² - 10x，求 f′(2)。','For f(x)=3x²-10x, find f′(2).',2,'导数'),makeHardQuestion(p+'2','number','矩阵 [[6,4],[5,3]] 的行列式是多少？','Find det([[6,4],[5,3]]).',-2,'矩阵'),makeHardQuestion(p+'3','number','等比数列首项 3，公比 4，第 4 项是多少？','Geometric sequence: first term 3, ratio 4. Find term 4.',192,'数列'),makeHardQuestion(p+'4','number','log₂(2^7) + 3 = ?','log₂(2^7) + 3 = ?',10,'对数'),makeHardQuestion(p+'5','number','从 12 个不同元素中选 2 个，有多少种组合？','How many combinations choose 2 from 12?',66,'组合')]}
if(subject==='science'){const topics=['变量控制','模型证据','系统反馈','能量守恒','科学论证'],good='需要设置对照组并控制变量后再解释结果。',bad=['一次现象足以证明结论永远成立。','不符合预期的数据应直接删除。','相关性一定等于因果关系。'];return topics.map((t,i)=>makeHardQuestion(p+(i+1),'mc','困难科学推理：研究“'+t+'”时，哪项结论最可靠？','Hard science reasoning: which conclusion is most reliable?',0,t,[good,...bad]))}
const words=[['corroborate','用证据证实'],['mitigate','减轻严重程度'],['perspicacious','有敏锐洞察力'],['inexorable','不可阻挡的']];return words.map((x,i)=>makeHardQuestion(p+(i+1),'meaning','困难词汇：'+x[0]+' 最接近哪项含义？','Hard vocabulary: '+x[0],0,'学术词汇',[x[1],'忽略证据','临时随意改变','完全无关'])).concat([makeHardQuestion(p+'5','reading','阅读：可靠论证必须由可核查证据支撑。哪项概括正确？','A sound argument rests on verifiable evidence. Which summary is correct?',0,'阅读推理',['可靠论证依赖可核查证据。','重复即可替代证据。','证据会削弱论证。','所有断言同样可靠。'])])}

function goHome(){home.hidden=false;setup.hidden=true;quizView.hidden=true;subject='none';questions=[];quizStartedAt=0;crumb.textContent='';hardMode=false;document.body.classList.remove('hard-mode');applyAdminMode();langToggle.hidden=false;hardModeToggle.style.display='none';hardModeToggle.classList.remove('is-on');hardModeToggle.setAttribute('aria-pressed','false');hardModeText.textContent=lang==='zh'?'困难':'HARD';updateDash()}
function selectSubject(s){if(!banks[s])return error('题库尚未加载完成。');subject=s;hardModeToggle.style.display='flex';if(s==='english'){langToggle.hidden=true;setLang('en')}else langToggle.hidden=false;home.hidden=true;setup.hidden=false;quizView.hidden=true;crumb.textContent='> '+T[lang][s];populate()}
function populate(){const allowed=allowedLevelIds(subject),available=banks[subject].levels.filter(level=>!allowed||allowed.has(String(level.id)));setupNote.textContent=lang==='zh'?`管理员已开放 ${available.length} 个等级；每次最多随机抽取 5 道不重复题目。`:`${available.length} level(s) are enabled by the administrator. Each quiz selects up to 5 unique questions.`;levels.innerHTML='';available.forEach(l=>{const o=document.createElement('option');o.value=l.id;o.textContent=tx(l.name);levels.append(o)});start.disabled=!available.length;if(!available.length)error(lang==='zh'?'管理员尚未开放这个学科的题目等级。':'No levels are enabled for this subject.')}
function questionKey(q){return JSON.stringify([q.type,q.question,q.passage,q.options]);}
function selectBalanced(pool,count,previous){
  const fresh=shuffle(pool.filter(q=>!previous.has(q.id))), seen=shuffle(pool.filter(q=>previous.has(q.id)));
  const source=[...fresh,...seen], chosen=[], used=new Set(), usedTopics=new Set(), usedTypes=new Set();
  for(const prefer of ['type','knowledge','any']) for(const q of source){
    if(chosen.length>=count||used.has(questionKey(q)))continue;
    const topic=tx(q.knowledge)||'general', type=q.type||'general';
    if(prefer==='type'&&usedTypes.has(type))continue;
    if(prefer==='knowledge'&&usedTopics.has(topic))continue;
    chosen.push(q);used.add(questionKey(q));usedTopics.add(topic);usedTypes.add(type);
  }
  return chosen;
}
function startQuiz(){const bank=hardMode?hardBanks[subject]:banks[subject],level=bank?.levels.find(l=>l.id===levels.value),allowed=allowedLevelIds(subject);if(allowed&&!allowed.has(String(levels.value)))return error(lang==='zh'?'这个等级未被管理员开放。':'This level is not enabled by the administrator.');if(!level?.questions?.length)return error(lang==='zh'?'当前等级没有题目。':'No questions found for this level.');const pool=[...new Map(level.questions.map(q=>[questionKey(q),q])).values()],count=Math.min(TOTAL,pool.length),key=`gongxing_last_quiz:${hardMode?'hard':'normal'}:${subject}:${level.id}`,previous=new Set(JSON.parse(sessionStorage.getItem(key)||'[]'));questions=selectBalanced(pool,count,previous);sessionStorage.setItem(key,JSON.stringify(questions.map(q=>q.id)));questions=questions.map(source=>{const q=clone(source);q.levelId=level.id;q.levelName=level.name;if(q.type!=='number'){const a=shuffle(q.options.map((o,n)=>({o,ok:n===q.answer})));q.options=a.map(x=>x.o);q.answer=a.findIndex(x=>x.ok)}return q});answers=Array(questions.length).fill(null);current=0;graded=false;quizStartedAt=Date.now();setup.hidden=true;quizView.hidden=false;score.style.display='none';dots.innerHTML=questions.map((_,i)=>'<i class=\"dot\" onclick=\"jump('+i+')\"></i>').join('');render()}
function render(){const q=questions[current],lastIndex=questions.length-1;document.querySelectorAll('.dot').forEach((d,i)=>d.className=`dot ${i===current?'active':''} ${!graded&&answers[i]!==null?'answered':''} ${graded?(correct(i)?'correct':'wrong'):''}`);prev.disabled=current===0;next.style.display=current===lastIndex?'none':'';submit.style.display=!graded&&current===lastIndex?'':'none';if(graded&&current===lastIndex)next.style.display='none';let h='';if(q.type==='number'){h=`<p class="qsub">${T[lang].types.number}</p><div class="question">${esc(tx(q.question))}</div><input class="answer" type="number" step="any" placeholder="${T[lang].placeholder}" value="${answers[current]??''}" oninput="save(this.value)" ${graded?'disabled':''}>`}else{h=`<p class="qsub">${T[lang].types[q.type]||T[lang].types.mc}</p>${q.type==='reading'?`<div class="passage">${esc(tx(q.passage))}</div>`:''}<div class="question">${esc(tx(q.question))}</div><div class="choices">${q.options.map((o,i)=>`<button class="choice ${answers[current]===i?'selected':''} ${graded?(i===q.answer&&answers[current]===i?'good':answers[current]===i?'bad':i===q.answer?'missed':''):''}" onclick="save(${i})" ${graded?'disabled':''}>${esc(tx(o))}</button>`).join('')}</div>`}if(graded){const ok=correct(current),ans=q.type==='number'?q.answer:tx(q.options[q.answer]);h+=`<p class="feedback ${ok?'good':'bad'}">${esc(answers[current]===null?T[lang].empty(ans):ok?T[lang].correct:T[lang].wrong(ans))}</p>`;quiz.className='quiz '+(ok?'correct':'wrong')}else quiz.className='quiz';content.innerHTML=h}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function save(v){if(graded)return;const isNumber=questions[current].type==='number';answers[current]=isNumber?(v===''?null:Number(v)):v;if(!isNumber)render()}function nav(n){current+=n;render()}function jump(i){current=i;render()}function correct(i){const q=questions[i],a=answers[i];return a!==null&&(q.type==='number'?Math.abs(a-q.answer)<EPS:Number(a)===Number(q.answer))}
function submitQuiz(){
  if(graded||!questions.length)return;
  if(!confirm(lang==='zh'?'确定要提交并批改吗？':'Submit and grade now?'))return;
  graded=true;
  const total=questions.length,n=questions.filter((_,i)=>correct(i)).length,bonus=total===5&&n===5?1:0,earned=n+bonus,beforePoints=Math.max(0,Math.floor(Number(user.points)||0)),todayDate=new Date().toLocaleDateString();
  if(user.lastDate!==todayDate){user.streak++;user.lastDate=todayDate}
  user.todaySolved+=total;user.totalSolved+=total;user.totalCorrect+=n;user.mastery[subject]+=n;user.quizCount+=1;user.points=Math.min(adminSettings.pointCap,Math.max(0,Math.floor(Number(user.points)||0))+earned);
  if(n===total)user.perfectQuizzes+=1;
  questions.forEach((q,i)=>{if(!correct(i))user.wrongBook.push({questionId:q.id,subject,level:q.levelId,date:new Date().toISOString()})});
  recordQuizUsage({id:questions[0].levelId,name:questions[0].levelName},total,n);quizStartedAt=0;
  saveUser();updateDash();
  const credited=user.points-beforePoints,r=n/total,capNote=credited<earned?(lang==='zh'?'（已达积分上限）':' (point cap reached)'):'',earnedText=lang==='zh'?` 本次获得 ${credited} 积分${bonus?'（含满分奖励 1 分）':''}${capNote}，余额 ${user.points}。`:` You earned ${credited} point${credited===1?'':'s'}${bonus?' (including a 1-point perfect bonus)':''}${capNote}. Balance: ${user.points}.`;
  score.style.display='block';score.textContent=T[lang].score(n,total)+earnedText;score.style.color=r>=.8?'var(--success)':r>=.6?'var(--warning)':'var(--error)';score.style.borderColor=score.style.color;score.style.background=r>=.8?'#10b9811a':r>=.6?'#f59e0b1a':'#ef44441a';current=0;render()
}
