const battleShipTypes=[{id:1,len:5,icon:'🛳️',name:'航空母舰'},{id:2,len:4,icon:'🚢',name:'战列舰'},{id:3,len:3,icon:'⛴️',name:'巡洋舰'},{id:4,len:3,icon:'🚤',name:'驱逐舰'},{id:5,len:2,icon:'🛥️',name:'巡逻艇'}];
function battleEmptyFleet(){return{cells:Array(64).fill(0),ships:[]}}
function battleSlots(start,len,horizontal){const r=Math.floor(start/8),c=start%8;if(horizontal&&c+len>8||!horizontal&&r+len>8)return null;return Array.from({length:len},(_,i)=>start+(horizontal?i:i*8))}
function battleFleet(){
  const fleet=battleEmptyFleet();
  battleShipTypes.forEach(type=>{let placed=false;while(!placed){const horizontal=Math.random()<.5,start=Math.floor(Math.random()*64),slots=battleSlots(start,type.len,horizontal);if(slots&&slots.every(x=>!fleet.cells[x])){slots.forEach(x=>fleet.cells[x]=type.id);fleet.ships.push({...type,cells:slots,horizontal});placed=true}}});
  return fleet;
}
function battleSunk(fleet,shots,id){const ship=fleet.ships.find(s=>s.id===id);return!!ship&&ship.cells.every(i=>shots.has(i))}
function battleLost(fleet,shots){return fleet.ships.every(s=>battleSunk(fleet,shots,s.id))}
function initBattleship(){
  canvas.hidden=true;dom.hidden=false;directControls(L('点击舰船、海域格和部署按钮操作','Tap ships, sea cells, and deployment controls'));const g={score:0,loop:false,mode:'ai',difficulty:'normal',onlinePlayer:0,onlineReady:[false,false],started:false,fleets:[],shots:[],turn:0,locked:false,timer:0,aiQueue:[],placingPlayer:0,selectedShip:1,horizontal:true,notice:''};
  const reset=(mode,difficulty,player=0)=>{g.mode=mode;g.difficulty=difficulty;g.onlinePlayer=player;g.onlineReady=[false,false];g.fleets=[battleEmptyFleet(),g.mode==='ai'?battleFleet():battleEmptyFleet()];g.shots=[new Set(),new Set()];g.turn=0;g.locked=false;g.aiQueue=[];g.placingPlayer=player;g.selectedShip=1;g.horizontal=true;g.started=true;renderPlacement()};
  const setup=()=>{setStatus('选择模式');dom.innerHTML=`<div class="mode-panel"><h3>⚓ 建立舰队</h3><p>每位玩家亲自部署五艘战舰：5 格、4 格、3 格、3 格和 2 格。命中可以继续开火，打空才交换回合。</p><div class="setup-grid"><label class="setup-field">对战模式<select id="battleMode"><option value="ai">对战电脑</option><option value="pvp">本地双人</option>${onlineOption()}</select></label><label class="setup-field" id="battleDifficultyField">电脑难度<select id="battleDifficulty"><option value="easy">侦察兵</option><option value="normal" selected>舰长</option><option value="hard">海军上将</option></select></label></div><button class="setup-start" id="battleStart">开始部署</button><p class="setup-online-note">${onlineStatusCopy()}</p></div>`;const mode=$('#battleMode'),field=$('#battleDifficultyField');mode.onchange=()=>field.hidden=mode.value!=='ai';$('#battleStart').onclick=()=>mode.value==='online'?matchOnline():reset(mode.value,$('#battleDifficulty').value)};
  const matchOnline=async()=>{dom.innerHTML=`<div class="mode-panel"><h3>${L('正在寻找海战对手…','Finding a Battleship opponent…')}</h3><p>${L('双方舰队只保存在各自设备，服务器仅转发射击与结果。','Fleets stay on each device; the server only relays shots and results.')}</p></div>`;try{await beginOnlineMatch('battleship',{found:(_,player)=>reset('online','normal',player-1),event:onlineEvent,closed:()=>finish(L('对手已离开','Opponent left'))})}catch{setup()}};
  const onlineEvent=event=>{if(g.mode!=='online')return;const other=1-g.onlinePlayer;if(event.type==='ready'){g.onlineReady[other]=true;if(g.onlineReady[g.onlinePlayer]){g.locked=false;renderBattle()}}else if(event.type==='shot'){const i=Number(event.payload?.index);if(g.turn!==other||g.shots[g.onlinePlayer].has(i))return;g.shots[g.onlinePlayer].add(i);const hit=!!g.fleets[g.onlinePlayer].cells[i],lost=battleLost(g.fleets[g.onlinePlayer],g.shots[g.onlinePlayer]);sendOnlineEvent('shot-result',{index:i,hit,lost}).catch(()=>{});if(lost)return win(other);if(!hit)g.turn=g.onlinePlayer;renderBattle()}else if(event.type==='shot-result'){const i=Number(event.payload?.index),hit=event.payload?.hit===true,lost=event.payload?.lost===true;g.shots[other].add(i);if(hit)g.fleets[other].cells[i]=99;g.locked=false;if(lost)return win(g.onlinePlayer);if(!hit)g.turn=other;g.notice=hit?'命中！你继续射击':'未命中，交换回合';renderBattle()}};
  const passScreen=(title,text,button,next)=>{setStatus('隐私交接');dom.innerHTML=`<div class="pass-screen"><div><div class="pass-icon">🔒</div><h3>${title}</h3><p>${text}</p><button class="setup-start" id="passBattle">${button}</button></div></div>`;$('#passBattle').onclick=next};
  const removeShip=(fleet,id)=>{const ship=fleet.ships.find(s=>s.id===id);if(!ship)return;ship.cells.forEach(i=>fleet.cells[i]=0);fleet.ships=fleet.ships.filter(s=>s.id!==id)};
  const chooseShip=id=>{const fleet=g.fleets[g.placingPlayer];removeShip(fleet,id);g.selectedShip=id;renderPlacement()};
  const placeAt=start=>{const fleet=g.fleets[g.placingPlayer],type=battleShipTypes.find(s=>s.id===g.selectedShip),slots=battleSlots(start,type.len,g.horizontal);if(!slots||slots.some(i=>fleet.cells[i])){g.notice='这里放不下，请换一个起点或旋转舰船。';return renderPlacement()}removeShip(fleet,type.id);slots.forEach(i=>fleet.cells[i]=type.id);fleet.ships.push({...type,cells:slots,horizontal:g.horizontal});g.notice=`${type.icon} ${type.name}部署完成`;g.selectedShip=battleShipTypes.find(s=>!fleet.ships.some(x=>x.id===s.id))?.id||type.id;renderPlacement()};
  const placementReady=()=>{const fleet=g.fleets[g.placingPlayer];if(fleet.ships.length<5)return;if(g.mode==='online'){g.onlineReady[g.onlinePlayer]=true;g.locked=true;sendOnlineEvent('ready',{}).catch(()=>{});if(g.onlineReady[1-g.onlinePlayer]){g.locked=false;renderBattle()}else{dom.innerHTML=`<div class="pass-screen"><div><div class="pass-icon">⌛</div><h3>${L('等待对手完成部署','Waiting for opponent')}</h3><p>${L('你的舰队已锁定。','Your fleet is locked.')}</p></div></div>`}return}if(g.mode==='pvp'&&g.placingPlayer===0){g.placingPlayer=1;g.selectedShip=1;g.notice='';passScreen('交给玩家 2','玩家 1 的舰队已经隐藏，请确认玩家 1 离开屏幕。','开始部署玩家 2 舰队',renderPlacement)}else{g.turn=0;g.notice='';if(g.mode==='pvp')passScreen('准备开战','双方舰队均已锁定。请把设备交给玩家 1。','玩家 1 开始射击',renderBattle);else renderBattle()}};
  const renderPlacement=()=>{const fleet=g.fleets[g.placingPlayer],player=g.mode==='ai'?'你的':`玩家 ${g.placingPlayer+1} 的`,icons=battleShipTypes.reduce((m,s)=>(m[s.id]=s.icon,m),{});setStatus(`${player}舰队部署 ${fleet.ships.length}/5`);const grid=fleet.cells.map((id,i)=>`<button class="sea-cell ${id?'ship':''}" data-place="${i}" aria-label="部署格 ${i+1}">${id?`<span class="vessel">${icons[id]}</span>`:''}</button>`).join('');const dock=battleShipTypes.map(s=>{const placed=fleet.ships.some(x=>x.id===s.id);return`<button class="ship-card ${g.selectedShip===s.id?'selected':''} ${placed?'placed':''}" data-ship="${s.id}"><span class="ship-icon">${s.icon}</span><span class="ship-detail"><strong>${s.name}</strong><span>${s.len} 格 · ${placed?'已部署，点击可重放':'等待部署'}</span></span><span>${placed?'✓':'→'}</span></button>`}).join('');dom.innerHTML=`<div class="game-toolbar"><strong>${player}舰队</strong><button class="mini-btn" id="battleConfig">模式设置</button></div>${g.notice?`<div class="battle-callout">${g.notice}</div>`:''}<div class="placement-layout"><div class="sea-wrap"><h4>部署海域 · 点击格子放置</h4><div class="sea-board">${grid}</div></div><div><p class="placement-hint">选择一艘船，再点击棋盘作为舰首位置。已部署的舰船可以点击后重新摆放。</p><div class="ship-dock">${dock}</div><div class="placement-actions"><button class="mini-btn" id="rotateShip">旋转：${g.horizontal?'横向':'纵向'}</button><button class="mini-btn" id="randomFleet">随机部署</button><button class="mini-btn" id="clearFleet">清空</button></div><button class="setup-start ready-btn" id="fleetReady" ${fleet.ships.length<5?'disabled':''}>锁定舰队 ${fleet.ships.length}/5</button></div></div>`;dom.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>placeAt(+b.dataset.place));dom.querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>chooseShip(+b.dataset.ship));$('#rotateShip').onclick=()=>{g.horizontal=!g.horizontal;renderPlacement()};$('#randomFleet').onclick=()=>{g.fleets[g.placingPlayer]=battleFleet();g.notice='已随机部署，可继续手动调整';renderPlacement()};$('#clearFleet').onclick=()=>{g.fleets[g.placingPlayer]=battleEmptyFleet();g.selectedShip=1;g.notice='舰队已清空';renderPlacement()};$('#fleetReady').onclick=placementReady;$('#battleConfig').onclick=setup};
  const remaining=(fleet,shots)=>fleet.ships.filter(s=>!battleSunk(fleet,shots,s.id)).length;
  const cellHTML=(fleet,shots,index,reveal,target)=>{const id=fleet.cells[index],shot=shots.has(index),sunk=id&&battleSunk(fleet,shots,id),icon=battleShipTypes.find(s=>s.id===id)?.icon||'';const cls=['sea-cell',reveal&&id?'ship':'',shot?(id?'hit':'miss'):'',sunk?'sunk':''].join(' ');return`<button class="${cls}" data-sea="${target?index:''}" ${!target||shot||g.locked||g.mode==='online'&&g.turn!==g.onlinePlayer?'disabled':''} aria-label="${shot?(id?'命中':'未命中'):'未知海域'}">${(reveal&&id||sunk)?`<span class="vessel">${icon}</span>`:''}</button>`};
  const boardHTML=(title,fleet,shots,reveal,target)=>`<div class="sea-wrap"><h4>${title}</h4><div class="sea-board">${fleet.cells.map((_,i)=>cellHTML(fleet,shots,i,reveal,target)).join('')}</div><div class="fleet-status">${g.mode==='online'&&target?'敌方舰队状态未知':`剩余战舰 ${remaining(fleet,shots)} / 5`}</div></div>`;
  const win=(winner)=>{g.score=g.mode==='ai'&&winner===0?Math.max(300,2200-g.shots[1].size*25):winner===0?1000:800;setScore(g.score);finish(g.mode==='ai'?(winner===0?'敌方舰队全灭':'我方舰队失联'):`玩家 ${winner+1} 获胜`)};
  const aiChoice=()=>{const open=Array.from({length:64},(_,i)=>i).filter(i=>!g.shots[0].has(i));if(g.difficulty==='easy')return open[Math.floor(Math.random()*open.length)];while(g.aiQueue.length){const i=g.aiQueue.shift();if(open.includes(i))return i}if(g.difficulty==='normal')return open[Math.floor(Math.random()*open.length)];let best=-1,candidates=[];for(const i of open){const r=Math.floor(i/8),c=i%8;let score=8-Math.abs(3.5-r)-Math.abs(3.5-c);for(const n of [i-8,i+8,i-1,i+1])if(n>=0&&n<64&&Math.abs(n%8-c)<=1&&g.shots[0].has(n)&&g.fleets[0].cells[n]&&!battleSunk(g.fleets[0],g.shots[0],g.fleets[0].cells[n]))score+=35;if(score>best){best=score;candidates=[i]}else if(score===best)candidates.push(i)}return candidates[Math.floor(Math.random()*candidates.length)]};
  const aiTurn=()=>{g.locked=true;setStatus('电脑正在锁定目标…');g.timer=setTimeout(()=>{if(ended||!g.started)return;const i=aiChoice(),hit=!!g.fleets[0].cells[i];g.shots[0].add(i);if(hit){const c=i%8;[i-8,i+8,i-1,i+1].forEach(n=>{if(n>=0&&n<64&&Math.abs(n%8-c)<=1&&!g.shots[0].has(n))g.aiQueue.push(n)})}if(battleLost(g.fleets[0],g.shots[0]))return win(1);if(hit){g.notice='电脑命中，继续射击';renderBattle();return aiTurn()}g.notice='电脑打空，轮到你';g.locked=false;g.turn=0;renderBattle()},g.difficulty==='easy'?520:g.difficulty==='hard'?850:680)};
  const fire=i=>{if(g.locked||ended)return;if(g.mode==='online'){if(g.turn!==g.onlinePlayer||g.shots[1-g.onlinePlayer].has(i))return;g.locked=true;g.notice='等待对手确认…';sendOnlineEvent('shot',{index:i}).catch(()=>{g.locked=false});return renderBattle()}const defender=g.turn===0?1:0,shots=g.shots[defender];if(shots.has(i))return;shots.add(i);const hit=!!g.fleets[defender].cells[i];if(battleLost(g.fleets[defender],shots))return win(g.turn);if(hit){g.notice=`命中！${g.mode==='ai'?'你':`玩家 ${g.turn+1}`}继续射击`;return renderBattle()}g.notice='未命中，交换回合';if(g.mode==='ai'){g.turn=1;g.locked=true;renderBattle();aiTurn()}else{g.turn=1-g.turn;passScreen(`交给玩家 ${g.turn+1}`,'上一位玩家打空，棋盘已经隐藏。',`玩家 ${g.turn+1} 继续`,renderBattle)}};
  const renderBattle=()=>{
    const player=g.mode==='ai'?0:g.mode==='online'?g.onlinePlayer:g.turn,enemy=1-player,own=g.fleets[player],target=g.fleets[enemy];setStatus(g.mode==='ai'?(g.turn===0?'你的回合':'电脑连续射击'):g.mode==='online'?(g.turn===player?'你的回合':'对手回合'):`玩家 ${player+1} 回合`);const label=g.mode==='ai'||g.mode==='online'?'你':`玩家 ${player+1}`;dom.innerHTML=`<div class="game-toolbar"><strong>${label}的作战终端</strong><button class="mini-btn" id="battleConfig">模式设置</button></div>${g.notice?`<div class="battle-callout">${g.notice}</div>`:''}<div class="battle-layout">${boardHTML('我方舰队',own,g.shots[player],true,false)}${boardHTML('敌方海域',target,g.shots[enemy],false,true)}</div>`;dom.querySelectorAll('[data-sea]').forEach(b=>{if(b.dataset.sea!=='')b.onclick=()=>fire(+b.dataset.sea)});$('#battleConfig').onclick=()=>{clearTimeout(g.timer);g.started=false;if(g.mode==='online')endOnlineMatch();setup()};
  };
  g.destroy=()=>{clearTimeout(g.timer);if(g.mode==='online')endOnlineMatch()};setup();return g;
}
renderLanguage();
updatePlayTimer();
accessTimer=setInterval(updatePlayTimer,250);
setInterval(flushPlayUsage,5000);
