function initGomoku(){
  canvas.hidden=true;dom.hidden=false;controls([]);canvas.width=720;canvas.height=720;canvas.className='gomoku';const size=15,margin=45,gap=45,g={score:0,board:Array(225).fill(0),turn:1,mode:'ai',difficulty:'normal',playing:false,hover:-1,lastMove:-1,moves:[],anim:null,particles:[],winLine:null,timer:0,texture:null};
  const setup=()=>{setStatus('选择模式');dom.hidden=false;canvas.hidden=true;dom.innerHTML=`<div class="mode-panel"><h3>⚫⚪ 曜石五子棋</h3><p>黑棋先行。电脑模式中你执黑棋；双人模式在同一设备轮流落子。</p><div class="setup-grid"><label class="setup-field">对战模式<select id="gomokuMode"><option value="ai">对战电脑</option><option value="pvp">本地双人</option></select></label><label class="setup-field" id="gomokuDifficultyField">电脑难度<select id="gomokuDifficulty"><option value="easy">入门</option><option value="normal" selected>棋手</option><option value="hard">宗师</option></select></label></div><button class="setup-start" id="gomokuStart">落子开局</button></div>`;const mode=$('#gomokuMode'),field=$('#gomokuDifficultyField');mode.onchange=()=>field.hidden=mode.value==='pvp';$('#gomokuStart').onclick=()=>start(mode.value,$('#gomokuDifficulty').value)};
  const makeTexture=()=>{const t=document.createElement('canvas');t.width=t.height=720;const x=t.getContext('2d'),base=x.createLinearGradient(0,0,720,720);base.addColorStop(0,'#f0c96e');base.addColorStop(.5,'#dca94f');base.addColorStop(1,'#c78b36');x.fillStyle=base;x.fillRect(0,0,720,720);let seed=9217;const random=()=>((seed=(seed*9301+49297)%233280)/233280);for(let i=0;i<260;i++){x.strokeStyle=`rgba(${90+random()*55},${42+random()*40},18,${.025+random()*.055})`;x.lineWidth=.5+random()*1.5;x.beginPath();const y=random()*720;x.moveTo(0,y);for(let px=0;px<=720;px+=60)x.lineTo(px,y+Math.sin(px*.018+random()*4)*4);x.stroke()}for(let i=0;i<180;i++){x.fillStyle=`rgba(82,38,16,${.025+random()*.055})`;x.beginPath();x.ellipse(random()*720,random()*720,2+random()*10,.5+random()*1.5,random()*3,0,7);x.fill()}return t};
  const start=(mode,difficulty)=>{g.mode=mode;g.difficulty=difficulty;g.board.fill(0);g.turn=1;g.playing=true;g.hover=-1;g.lastMove=-1;g.moves=[];g.anim=null;g.particles=[];g.winLine=null;g.texture=makeTexture();dom.hidden=true;canvas.hidden=false;controls([['悔棋','undo']]);setScore(0);setStatus('黑棋 · 落子');g.draw()};
  const rc=i=>[Math.floor(i/size),i%size],inside=(r,c)=>r>=0&&r<size&&c>=0&&c<size;
  const winAt=(i,p)=>{const [r,c]=rc(i);for(const [dr,dc] of [[1,0],[0,1],[1,1],[1,-1]]){const line=[i];for(let s=1;inside(r-dr*s,c-dc*s)&&g.board[(r-dr*s)*size+c-dc*s]===p;s++)line.unshift((r-dr*s)*size+c-dc*s);for(let s=1;inside(r+dr*s,c+dc*s)&&g.board[(r+dr*s)*size+c+dc*s]===p;s++)line.push((r+dr*s)*size+c+dc*s);if(line.length>=5)return[line[0],line[line.length-1]]}return null};
  const pattern=(i,p)=>{if(g.board[i])return-Infinity;g.board[i]=p;const [r,c]=rc(i);let score=0,forks=0;for(const [dr,dc] of [[1,0],[0,1],[1,1],[1,-1]]){let a=0,b=0;while(inside(r-(a+1)*dr,c-(a+1)*dc)&&g.board[(r-(a+1)*dr)*size+c-(a+1)*dc]===p)a++;while(inside(r+(b+1)*dr,c+(b+1)*dc)&&g.board[(r+(b+1)*dr)*size+c+(b+1)*dc]===p)b++;const total=a+b+1,openA=inside(r-(a+1)*dr,c-(a+1)*dc)&&!g.board[(r-(a+1)*dr)*size+c-(a+1)*dc],openB=inside(r+(b+1)*dr,c+(b+1)*dc)&&!g.board[(r+(b+1)*dr)*size+c+(b+1)*dc],open=+openA + +openB;if(total>=5)score+=10000000;else if(total===4)score+=open===2?700000:open===1?120000:0;else if(total===3)score+=open===2?45000:open===1?6500:0;else if(total===2)score+=open===2?2200:open===1?350:0;else score+=open*35;if(total>=3&&open)forks++}g.board[i]=0;return score+(forks>=2?forks*18000:0)};
  const candidates=()=>{if(!g.moves.length)return[112];const out=new Set;for(const m of g.moves){const [r,c]=rc(m.i);for(let dr=-2;dr<=2;dr++)for(let dc=-2;dc<=2;dc++){const rr=r+dr,cc=c+dc,i=rr*size+cc;if(inside(rr,cc)&&!g.board[i])out.add(i)}}return[...out]};
  const aiPick=()=>{const list=candidates();if(g.difficulty==='easy'){const close=list.filter(i=>pattern(i,2)>1500||pattern(i,1)>5000);const pool=close.length&&Math.random()>.35?close:list;return pool[Math.floor(Math.random()*pool.length)]}let best=-Infinity,choices=[];for(const i of list){const attack=pattern(i,2),defense=pattern(i,1);let value;if(attack>=10000000)value=9e8;else if(defense>=10000000)value=8e8;else value=attack*(g.difficulty==='hard'?1.22:1)+defense*(g.difficulty==='hard'?1.28:1.12)+(14-Math.abs(7-rc(i)[0])-Math.abs(7-rc(i)[1]))*10+Math.random()*18;if(value>best){best=value;choices=[i]}else if(Math.abs(value-best)<1)choices.push(i)}return choices[Math.floor(Math.random()*choices.length)]};
  const burst=i=>{const [r,c]=rc(i),x=margin+c*gap,y=margin+r*gap;for(let n=0;n<18;n++){const a=Math.random()*Math.PI*2,s=35+Math.random()*85;g.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.45+Math.random()*.35,t:0,color:g.turn===1?'#ffc85a':'#ffffff'})}};
  const place=(i,p)=>{if(!g.playing||g.board[i]||g.winLine)return;g.board[i]=p;g.moves.push({i,p});g.lastMove=i;g.anim={i,t:0};burst(i);const line=winAt(i,p);if(line){g.winLine=line;g.score=p===1?1600:500;setScore(g.score);setStatus(`${p===1?'黑棋':'白棋'}连成五子`);g.timer=setTimeout(()=>finish(`${p===1?'黑棋':'白棋'}获胜`),850);return}if(g.moves.length===225){g.timer=setTimeout(()=>finish('棋盘已满 · 和棋'),500);return}g.turn=p===1?2:1;setStatus(`${g.turn===1?'黑棋':'白棋'} · 落子`);if(g.mode==='ai'&&g.turn===2){setStatus('电脑正在思考…');g.timer=setTimeout(()=>place(aiPick(),2),g.difficulty==='hard'?520:320)}};
  const undo=()=>{if(!g.playing||g.winLine||!g.moves.length)return;clearTimeout(g.timer);const count=g.mode==='ai'?Math.min(2,g.moves.length):1;for(let n=0;n<count;n++){const m=g.moves.pop();g.board[m.i]=0}g.lastMove=g.moves.at(-1)?.i??-1;g.turn=g.mode==='ai'?1:(g.moves.at(-1)?.p===1?2:1);g.anim=null;g.particles=[];setStatus(`${g.turn===1?'黑棋':'白棋'} · 落子`)};
  g.action=(a,on)=>{if(a==='undo'&&on)undo()};
  const point=e=>{const b=canvas.getBoundingClientRect(),x=(e.clientX-b.left)*720/b.width,y=(e.clientY-b.top)*720/b.height,c=Math.round((x-margin)/gap),r=Math.round((y-margin)/gap);return inside(r,c)&&Math.hypot(x-(margin+c*gap),y-(margin+r*gap))<gap*.48?r*size+c:-1};
  canvas.onpointermove=e=>{if(!g.playing)return;g.hover=point(e)};canvas.onpointerleave=()=>g.hover=-1;canvas.onpointerdown=e=>{e.preventDefault();if(!g.playing||g.winLine||g.mode==='ai'&&g.turn===2)return;const i=point(e);if(i>=0&&!g.board[i])place(i,g.turn)};
  const stone=(x,y,p,r=20,alpha=1)=>{ctx.save();ctx.globalAlpha=alpha;ctx.shadowColor=p===1?'#000':'#fff';ctx.shadowBlur=8;const grad=ctx.createRadialGradient(x-7,y-8,2,x,y,r);if(p===1){grad.addColorStop(0,'#686868');grad.addColorStop(.22,'#262626');grad.addColorStop(.72,'#070707');grad.addColorStop(1,'#000')}else{grad.addColorStop(0,'#fff');grad.addColorStop(.35,'#f4f1e9');grad.addColorStop(.78,'#cbc6bb');grad.addColorStop(1,'#8e887d')}ctx.fillStyle=grad;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();ctx.strokeStyle=p===1?'#000':'#a69f91';ctx.lineWidth=1.3;ctx.stroke();ctx.restore()};
  g.update=dt=>{if(!g.playing)return;if(g.anim){g.anim.t+=dt;if(g.anim.t>.42)g.anim=null}for(const p of g.particles){p.t+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=80*dt}g.particles=g.particles.filter(p=>p.t<p.life)};
  g.draw=()=>{if(!g.playing)return;ctx.drawImage(g.texture,0,0);const inner=28,frame=12;ctx.save();ctx.strokeStyle='#4c2414';ctx.lineWidth=frame;ctx.strokeRect(inner,inner,664,664);ctx.strokeStyle='#f1ca71';ctx.lineWidth=2;ctx.strokeRect(inner+8,inner+8,648,648);ctx.restore();ctx.strokeStyle='rgba(24,18,11,.78)';ctx.lineWidth=1.35;for(let n=0;n<size;n++){ctx.beginPath();ctx.moveTo(margin,margin+n*gap);ctx.lineTo(margin+14*gap,margin+n*gap);ctx.stroke();ctx.beginPath();ctx.moveTo(margin+n*gap,margin);ctx.lineTo(margin+n*gap,margin+14*gap);ctx.stroke()}ctx.fillStyle='#24170e';for(const [r,c] of [[3,3],[3,7],[3,11],[7,3],[7,7],[7,11],[11,3],[11,7],[11,11]]){ctx.beginPath();ctx.arc(margin+c*gap,margin+r*gap,4.4,0,7);ctx.fill()}if(g.hover>=0&&!g.board[g.hover]&&!g.winLine){const [r,c]=rc(g.hover);stone(margin+c*gap,margin+r*gap,g.turn,19,.28)}for(let i=0;i<225;i++)if(g.board[i]){const [r,c]=rc(i),scale=g.anim?.i===i?Math.min(1,1+(1-Math.min(1,g.anim.t/.34))*Math.sin(Math.min(1,g.anim.t/.34)*Math.PI)*.3):1;stone(margin+c*gap,margin+r*gap,g.board[i],20*scale)}if(g.lastMove>=0){const [r,c]=rc(g.lastMove);ctx.strokeStyle='#ef4444';ctx.lineWidth=2.2;ctx.beginPath();ctx.arc(margin+c*gap,margin+r*gap,6,0,7);ctx.stroke()}for(const p of g.particles){ctx.globalAlpha=1-p.t/p.life;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,1.5+(1-p.t/p.life)*2,0,7);ctx.fill()}ctx.globalAlpha=1;if(g.anim){const [r,c]=rc(g.anim.i),pulse=24+g.anim.t*55;ctx.strokeStyle=`rgba(255,211,112,${Math.max(0,1-g.anim.t/.42)})`;ctx.lineWidth=3;ctx.beginPath();ctx.arc(margin+c*gap,margin+r*gap,pulse,0,7);ctx.stroke()}if(g.winLine){const [a,b]=g.winLine.map(rc),pulse=16+Math.sin(performance.now()/130)*5;ctx.save();ctx.strokeStyle='#ffdf78';ctx.lineWidth=7;ctx.shadowColor='#ffb300';ctx.shadowBlur=pulse;ctx.beginPath();ctx.moveTo(margin+a[1]*gap,margin+a[0]*gap);ctx.lineTo(margin+b[1]*gap,margin+b[0]*gap);ctx.stroke();ctx.restore()}};
  g.destroy=()=>clearTimeout(g.timer);setup();return g;
}
