const pacMaze=['###################','#o.......#.......o#','#.###.##.#.##.###.#','#.................#','#.###.#.###.#.###.#','#.....#..#..#.....#','#####.##.#.##.#####','#.....#.....#.....#','#.###.#.###.#.###.#','#.....#     #.....#','#####.# ### #.#####','     .       .     ','#####.# ### #.#####','#.....#.....#.....#','#.###.#.###.#.###.#','#...#.........#...#','###.#.##.#.##.#.###','#.....#..#..#.....#','#.######.#.######.#','#o...............o#','###################'];
function initPacman(){
  canvas.width=760;canvas.height=560;canvas.className='pacman';controls([
    {label:'←',ariaLabel:L('向左','Move left'),action:'left',slot:'left'},
    {label:'↑',ariaLabel:L('向上','Move up'),action:'up',slot:'up'},
    {label:'↓',ariaLabel:L('向下','Move down'),action:'down',slot:'down'},
    {label:'→',ariaLabel:L('向右','Move right'),action:'right',slot:'right'}
  ],{layout:'dpad'});
  const dirs={left:{x:-1,y:0},right:{x:1,y:0},up:{x:0,y:-1},down:{x:0,y:1}},opposite={left:'right',right:'left',up:'down',down:'up'},W=19,H=21,tile=24,ox=(760-W*tile)/2,oy=28;
  const g={score:0,lives:3,level:1,pellets:new Set(),power:new Set(),fright:0,combo:0,ready:1.4,phase:0,phaseTime:7,flash:0,player:null,ghosts:[],fruit:null,fruitTimer:0,extraLife:false};
  const key=(r,c)=>r*W+c,cell=(r,c)=>r===11&&(c<0||c>=W)?' ':pacMaze[r]?.[c]||'#',open=(r,c)=>cell(r,c)!=='#';
  const refill=()=>{g.pellets.clear();g.power.clear();pacMaze.forEach((row,r)=>[...row].forEach((v,c)=>{if(v==='.')g.pellets.add(key(r,c));if(v==='o')g.power.add(key(r,c))}))};
  const actor=(x,y,dir)=>({x,y,dir,next:dir});
  const resetActors=()=>{g.player=actor(9,15,'left');g.ghosts=[{...actor(9,9,'left'),color:'#ff304f',name:'red',home:0},{...actor(8,9,'up'),color:'#ff8bd1',name:'pink',home:.8},{...actor(10,9,'up'),color:'#25e6ee',name:'cyan',home:1.6},{...actor(9,10,'right'),color:'#ff9f31',name:'orange',home:2.4}];g.ready=1.35;g.fright=0;g.combo=0};
  const can=(a,d)=>{const v=dirs[d],r=Math.round(a.y),c=Math.round(a.x);return open(r+v.y,c+v.x)};
  const centered=a=>Math.abs(a.x-Math.round(a.x))<.012&&Math.abs(a.y-Math.round(a.y))<.012;
  const move=(a,speed,dt,decide)=>{let distance=speed*dt;while(distance>.0001){if(centered(a)){a.x=Math.round(a.x);a.y=Math.round(a.y);const choice=decide?.(a);if(choice&&can(a,choice))a.dir=choice;if(a.next&&can(a,a.next))a.dir=a.next;if(!can(a,a.dir))return}const v=dirs[a.dir],axis=v.x?a.x:a.y,raw=v.x<0||v.y<0?axis-Math.floor(axis):Math.ceil(axis)-axis,toCenter=raw<.001?1:raw,step=Math.min(distance,toCenter);a.x+=v.x*step;a.y+=v.y*step;distance-=step;if(a.y>10.55&&a.y<11.45){if(a.x<-.65)a.x=W-.35;if(a.x>W-.35)a.x=-.65}}};
  const targetFor=(gh)=>{const p=g.player,v=dirs[p.dir];if(g.phase===0){return gh.name==='red'?[18,0]:gh.name==='pink'?[0,0]:gh.name==='cyan'?[18,20]:[0,20]}if(gh.name==='pink')return[p.x+v.x*4,p.y+v.y*4];if(gh.name==='cyan')return[p.x+v.x*2+(p.x-9),p.y+v.y*2+(p.y-9)];if(gh.name==='orange'&&Math.hypot(gh.x-p.x,gh.y-p.y)<6)return[0,20];return[p.x,p.y]};
  const ghostDir=gh=>{if(gh.home>0)return gh.dir;const options=Object.keys(dirs).filter(d=>d!==opposite[gh.dir]&&can(gh,d));if(!options.length)return opposite[gh.dir];if(g.fright>0)return options[Math.floor(Math.random()*options.length)];const [tx,ty]=targetFor(gh);return options.sort((a,b)=>{const A=dirs[a],B=dirs[b];return Math.hypot(gh.x+A.x-tx,gh.y+A.y-ty)-Math.hypot(gh.x+B.x-tx,gh.y+B.y-ty)})[0]};
  const award=points=>{g.score+=points;if(!g.extraLife&&g.score>=10000){g.extraLife=true;g.lives++}setScore(g.score)};
  const eatAt=()=>{const r=Math.round(g.player.y),c=Math.round(g.player.x),k=key(r,c),before=g.pellets.size+g.power.size;if(g.pellets.delete(k))award(10);if(g.power.delete(k)){award(50);g.fright=7;g.combo=0;g.ghosts.forEach(gh=>gh.dir=opposite[gh.dir])}const left=g.pellets.size+g.power.size;if(left!==before&&(left===120||left===55)){g.fruit={x:9,y:15};g.fruitTimer=9}if(g.fruit&&Math.hypot(g.player.x-g.fruit.x,g.player.y-g.fruit.y)<.65){award(Math.min(500,100*g.level));g.fruit=null;g.fruitTimer=0}if(!left){g.level++;g.flash=1.1;g.fruit=null;g.fruitTimer=0;refill();resetActors()}};
  const loseLife=()=>{g.lives--;if(g.lives<=0)return finish(L('游戏结束','Game over'));resetActors()};
  g.action=(a,on)=>{if(on&&dirs[a])g.player.next=a};g.key=(k,on)=>{if(!on)return;const m={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down'};if(m[k])g.player.next=m[k]};
  let swipe=null;
  const steerFromSwipe=event=>{
    if(!swipe||event.pointerId!==swipe.pointerId)return;
    const dx=event.clientX-swipe.x,dy=event.clientY-swipe.y;
    if(Math.hypot(dx,dy)<18)return;
    g.player.next=Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down');
    swipe={pointerId:event.pointerId,x:event.clientX,y:event.clientY};
  };
  canvas.onpointerdown=event=>{
    if(event.pointerType==='mouse'&&event.button!==0)return;
    event.preventDefault();
    swipe={pointerId:event.pointerId,x:event.clientX,y:event.clientY};
    try{canvas.setPointerCapture(event.pointerId)}catch{}
  };
  canvas.onpointermove=event=>{event.preventDefault();steerFromSwipe(event)};
  canvas.onpointerup=event=>{steerFromSwipe(event);swipe=null};
  canvas.onpointercancel=()=>swipe=null;
  g.update=dt=>{g.flash=Math.max(0,g.flash-dt);if(g.ready>0){g.ready-=dt;setStatus(L(`准备！生命 ${g.lives} · 第 ${g.level} 关`,`READY! Lives ${g.lives} · Level ${g.level}`));return}g.phaseTime-=dt;if(g.phaseTime<=0){g.phase=1-g.phase;g.phaseTime=g.phase?20:7;g.ghosts.forEach(gh=>gh.dir=opposite[gh.dir])}g.fright=Math.max(0,g.fright-dt);if(g.fruit){g.fruitTimer-=dt;if(g.fruitTimer<=0)g.fruit=null}move(g.player,6.25,dt);eatAt();for(const gh of g.ghosts){gh.home=Math.max(0,gh.home-dt);if(gh.home>0)continue;move(gh,(g.fright>0?3.7:4.75+g.level*.12),dt,ghostDir);if(Math.hypot(gh.x-g.player.x,gh.y-g.player.y)<.62){if(g.fright>0){g.combo++;award(200*2**(g.combo-1));gh.x=9;gh.y=9;gh.home=1.4;gh.dir='up'}else{return loseLife()}}}setStatus(L(`第 ${g.level} 关 · 生命 ${g.lives} · 剩余 ${g.pellets.size+g.power.size}`,`Level ${g.level} · Lives ${g.lives} · ${g.pellets.size+g.power.size} left`))};
  const roundRect=(x,y,w,h,r)=>{ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.stroke()};
  const ghost=(gh,i)=>{const x=ox+(gh.x+.5)*tile,y=oy+(gh.y+.5)*tile,r=tile*.43,fright=g.fright>0&&gh.home<=0,blink=fright&&g.fright<2&&Math.floor(performance.now()/160)%2;ctx.save();ctx.translate(x,y);glow(fright?'#2355ff':gh.color,13);ctx.fillStyle=blink?'#f5f5f5':fright?'#234cff':gh.color;ctx.beginPath();ctx.arc(0,-1,r,Math.PI,0);ctx.lineTo(r,r);for(let n=0;n<3;n++){ctx.lineTo(r-n*r*2/3-r/3,n%2?r*.55:r);ctx.lineTo(r-(n+1)*r*2/3,n%2?r:r*.55)}ctx.lineTo(-r,-1);ctx.fill();resetGlow();if(!fright){const look=dirs[gh.dir];for(const ex of [-r*.38,r*.38]){ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(ex,-r*.12,r*.26,r*.32,0,0,7);ctx.fill();ctx.fillStyle='#173d9c';ctx.beginPath();ctx.arc(ex+look.x*r*.1,-r*.12+look.y*r*.1,r*.12,0,7);ctx.fill()}}else{ctx.fillStyle='#fff';for(const ex of [-r*.35,r*.35]){ctx.beginPath();ctx.arc(ex,-r*.08,r*.08,0,7);ctx.fill()}ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-r*.5,r*.35);ctx.lineTo(-r*.25,r*.2);ctx.lineTo(0,r*.35);ctx.lineTo(r*.25,r*.2);ctx.lineTo(r*.5,r*.35);ctx.stroke()}ctx.restore()};
  g.draw=()=>{ctx.fillStyle='#02030a';ctx.fillRect(0,0,760,560);const pulse=.75+Math.sin(performance.now()/180)*.2;for(let r=0;r<H;r++)for(let c=0;c<W;c++){const x=ox+c*tile,y=oy+r*tile;if(cell(r,c)==='#'){ctx.save();ctx.strokeStyle='#275dff';ctx.lineWidth=3;ctx.shadowColor='#153cff';ctx.shadowBlur=8;roundRect(x+2,y+2,tile-4,tile-4,6);ctx.restore()}const k=key(r,c);if(g.pellets.has(k)){ctx.fillStyle='#ffdcb2';ctx.beginPath();ctx.arc(x+tile/2,y+tile/2,2.3,0,7);ctx.fill()}if(g.power.has(k)){ctx.fillStyle='#fff1cf';glow('#fff',10);ctx.beginPath();ctx.arc(x+tile/2,y+tile/2,5.2*pulse,0,7);ctx.fill();resetGlow()}}if(g.fruit){const fx=ox+(g.fruit.x+.5)*tile,fy=oy+(g.fruit.y+.5)*tile;ctx.save();ctx.translate(fx,fy);glow('#ff274d',12);ctx.fillStyle='#ff294d';ctx.beginPath();ctx.arc(-5,4,6,0,7);ctx.arc(5,4,6,0,7);ctx.fill();ctx.strokeStyle='#54d878';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-5,-1);ctx.quadraticCurveTo(0,-12,7,-8);ctx.moveTo(5,-1);ctx.quadraticCurveTo(4,-9,7,-8);ctx.stroke();ctx.restore();resetGlow()}for(let i=0;i<g.ghosts.length;i++)ghost(g.ghosts[i],i);const p=g.player,x=ox+(p.x+.5)*tile,y=oy+(p.y+.5)*tile,a={right:0,down:Math.PI/2,left:Math.PI,up:-Math.PI/2}[p.dir],mouth=.16+.22*Math.abs(Math.sin(performance.now()/105));ctx.save();ctx.translate(x,y);glow('#ffd91a',14);ctx.fillStyle='#ffe01b';ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,tile*.43,a+mouth*Math.PI,a+(2-mouth)*Math.PI);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#ffe01b';ctx.font='800 17px sans-serif';ctx.fillText(L(`得分 ${g.score}`,`SCORE ${g.score}`),24,28);ctx.textAlign='right';ctx.fillText(L(`第 ${g.level} 关`,`LEVEL ${g.level}`),736,28);ctx.textAlign='left';for(let i=0;i<g.lives;i++){ctx.beginPath();ctx.moveTo(27+i*24,538);ctx.arc(27+i*24,538,9,.22*Math.PI,1.78*Math.PI);ctx.closePath();ctx.fill()}if(g.ready>0){ctx.textAlign='center';ctx.font='900 25px sans-serif';ctx.fillStyle='#ffe01b';ctx.fillText(L('准备！','READY!'),380,292);ctx.textAlign='left'}if(g.flash>0){ctx.fillStyle=`rgba(255,255,255,${g.flash*.28})`;ctx.fillRect(0,0,760,560)}};
  refill();resetActors();setScore(0);return g;
}
