const forestLevels=[{
  n:['森林神殿 · 初始试炼','Forest Temple · First Trial'],
  s:[[54,614],[102,614]],
  p:[[0,658,900,32],[0,570,322,18],[310,588,480,18],[0,466,392,18],[382,484,448,18],[0,355,398,18],[388,375,438,18],[0,253,390,18],[380,272,430,18],[210,190,190,18],[205,139,695,18]],
  h:[[410,644,95,'fire'],[590,644,95,'water'],[566,574,90,'acid']],
  j:[[52,214,'water'],[236,100,'fire'],[421,222,'fire'],[514,104,'water'],[160,425,'fire'],[535,335,'water'],[468,548,'fire'],[690,445,'water']],
  b:[[235,562,'lowerLift','any'],[660,367,'upperLift','any']],
  g:[[448,190,28,82,'lowerLift'],[752,70,24,69,'upperLift']],
  m:[[22,548,22,510,92,14,.7,'yellow'],[760,359,760,315,86,14,.76,'purple'],[218,347,218,310,74,14,.82,'purple']],
  d:[[801,80,'fire'],[844,80,'water']]
}];
const forestBackground=new Image();
function initForestTwins(){
  canvas.width=900;canvas.height=690;canvas.className='forest-twins';controls([['🔥←','fl'],['🔥↑','fj'],['🔥→','fr'],['💧←','wl'],['💧↑','wj'],['💧→','wr']]);
  const g={score:0,level:0,time:0,keys:{},actors:[],gems:[],opened:new Set(),movers:[],complete:0,particles:[]};
  const rect=(x,y,w,h)=>({x,y,w,h}),hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
  const level=()=>forestLevels[g.level],actor=(type,pos)=>({type,x:pos[0],y:pos[1],w:25,h:36,vx:0,vy:0,ground:false,door:false});
  const load=()=>{const l=level();g.actors=[actor('fire',l.s[0]),actor('water',l.s[1])];g.gems=(l.j||[]).map((v,i)=>({x:v[0],y:v[1],type:v[2],taken:false,i}));g.opened.clear();g.movers=(l.m||[]).map(v=>({a:v[0],b:v[2],ay:v[1],by:v[3],x:v[0],y:v[1],w:v[4],h:v[5],speed:v[6],color:v[7]||'yellow',t:0,prevY:v[1]}));g.complete=0;g.time=0;setStatus(L(l.n[0],l.n[1]))};
  const solids=()=>{const l=level(),base=(l.p||[]).map(v=>rect(...v)),gates=(l.g||[]).filter(v=>!g.opened.has(v[4])).map(v=>rect(v[0],v[1],v[2],v[3]));return base.concat(gates,g.movers.map(m=>rect(m.x,m.y,m.w,m.h)))};
  const resetActor=a=>{const p=level().s[a.type==='fire'?0:1];a.x=p[0];a.y=p[1];a.vx=a.vy=0;for(let i=0;i<14;i++)g.particles.push({x:a.x+12,y:a.y+18,vx:(Math.random()-.5)*160,vy:-Math.random()*120,t:0,c:a.type==='fire'?'#ff6534':'#42c7ff'})};
  const moveActor=(a,dt)=>{const left=g.keys[a.type==='fire'?'fl':'wl'],right=g.keys[a.type==='fire'?'fr':'wr'],jump=g.keys[a.type==='fire'?'fj':'wj'];a.vx=(right-left)*205;if(jump&&a.ground){a.vy=-520;a.ground=false}a.vy=Math.min(780,a.vy+1120*dt);a.x+=a.vx*dt;for(const s of solids())if(hit(a,s)){if(a.vx>0)a.x=s.x-a.w;else if(a.vx<0)a.x=s.x+s.w}a.y+=a.vy*dt;a.ground=false;for(const s of solids())if(hit(a,s)){if(a.vy>0){a.y=s.y-a.h;a.vy=0;a.ground=true}else if(a.vy<0){a.y=s.y+s.h;a.vy=0}}a.x=Math.max(0,Math.min(900-a.w,a.x));if(a.y>710)resetActor(a)};
  const updateWorld=dt=>{const l=level();for(const m of g.movers){m.prevY=m.y;m.t+=dt*m.speed;const q=(Math.sin(m.t)+1)/2;m.x=m.a+(m.b-m.a)*q;m.y=m.ay+(m.by-m.ay)*q}for(const a of g.actors)moveActor(a,dt);for(const plate of l.b||[]){const r=rect(plate[0],plate[1]-7,38,15),need=plate[3];if(g.actors.some(a=>(need==='any'||a.type===need)&&hit(a,r)))g.opened.add(plate[2])}for(const a of g.actors)for(const gem of g.gems)if(!gem.taken&&gem.type===a.type&&hit(a,rect(gem.x,gem.y,20,28))){gem.taken=true;g.score+=150;setScore(g.score)}for(const pool of l.h||[])for(const a of g.actors)if(hit(a,rect(pool[0],pool[1],pool[2],14))&&(pool[3]==='acid'||pool[3]!==a.type))resetActor(a);const doors=(l.d||[]).map(v=>({x:v[0],y:v[1],w:36,h:59,type:v[2]})),all=g.gems.every(x=>x.taken);for(const a of g.actors)a.door=all&&hit(a,doors.find(d=>d.type===a.type));if(all&&g.actors.every(a=>a.door)&&!g.complete){g.complete=1.1;g.score+=Math.max(300,1800-Math.floor(g.time)*8);setScore(g.score)}};
  g.action=(k,on)=>g.keys[k]=on?1:0;g.key=(k,on)=>{const map={ArrowLeft:'fl',ArrowUp:'fj',ArrowRight:'fr',a:'wl',A:'wl',w:'wj',W:'wj',d:'wr',D:'wr'};if(map[k])g.keys[map[k]]=on?1:0};
  g.update=dt=>{g.time+=dt;for(const p of g.particles){p.t+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=260*dt}g.particles=g.particles.filter(p=>p.t<.7);if(g.complete>0){g.complete-=dt;if(g.complete<=0)return finish(L('森林圣殿已净化','Forest sanctuary restored'));return}updateWorld(dt);const left=g.gems.filter(x=>!x.taken).length;setStatus(L(`宝石剩余 ${left} · ${Math.floor(g.time)} 秒`,`Gems left ${left} · ${Math.floor(g.time)}s`))};
  const drawTemple=()=>{if(forestBackground.complete&&forestBackground.naturalWidth){ctx.drawImage(forestBackground,0,0,900,690);ctx.fillStyle='rgba(5,12,5,.08)';ctx.fillRect(0,0,900,690);return}const bg=ctx.createLinearGradient(0,0,0,690);bg.addColorStop(0,'#17200d');bg.addColorStop(1,'#263017');ctx.fillStyle=bg;ctx.fillRect(0,0,900,690)};
  const drawPlatform=s=>{const grad=ctx.createLinearGradient(0,s.y,0,s.y+s.h);grad.addColorStop(0,'#93a76a');grad.addColorStop(.18,'#566b42');grad.addColorStop(1,'#2d3528');ctx.fillStyle=grad;ctx.fillRect(s.x,s.y,s.w,s.h);ctx.fillStyle='#98c273';ctx.fillRect(s.x,s.y,s.w,4)};
  const drawActor=a=>{const c=a.type==='fire'?'#ff5b2e':'#37bfff',x=a.x+a.w/2,y=a.y+a.h/2;ctx.save();ctx.translate(x,y);glow(c,12);ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(-11,-14,22,29,8);ctx.fill();ctx.beginPath();if(a.type==='fire'){ctx.moveTo(-7,-14);ctx.quadraticCurveTo(0,-31,7,-14)}else{ctx.moveTo(-8,-14);ctx.quadraticCurveTo(0,-29,8,-14)}ctx.fill();resetGlow();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-4,-4,3,0,7);ctx.arc(4,-4,3,0,7);ctx.fill();ctx.fillStyle='#17202b';ctx.beginPath();ctx.arc(-3,-4,1.3,0,7);ctx.arc(5,-4,1.3,0,7);ctx.fill();ctx.restore()};
  g.draw=()=>{drawTemple();const l=level(),hasArt=forestBackground.complete&&forestBackground.naturalWidth;if(!hasArt)for(const p of l.p||[])drawPlatform(rect(...p));for(const m of g.movers){const c=m.color==='purple'?'#d22cff':'#ffd42f';ctx.fillStyle=c;glow(c,12);ctx.fillRect(m.x,m.y,m.w,m.h);ctx.fillStyle='#fff6';ctx.fillRect(m.x+5,m.y+2,m.w-10,3);resetGlow()}for(const pool of l.h||[]){const colors={fire:'#ff3b19',water:'#2cbcff',acid:'#55d12c'},c=colors[pool[3]];ctx.fillStyle=c;glow(c,15);ctx.beginPath();ctx.moveTo(pool[0],pool[1]+4);for(let x=0;x<=pool[2];x+=8)ctx.lineTo(pool[0]+x,pool[1]+3+Math.sin(performance.now()/180+x*.24)*3);ctx.lineTo(pool[0]+pool[2],pool[1]+14);ctx.lineTo(pool[0],pool[1]+14);ctx.closePath();ctx.fill();resetGlow()}for(const gate of l.g||[])if(!g.opened.has(gate[4])){const gr=ctx.createLinearGradient(gate[0],gate[1],gate[0]+gate[2],gate[1]+gate[3]);gr.addColorStop(0,'#d7d3bd');gr.addColorStop(.5,'#fffdf1');gr.addColorStop(1,'#8b8a77');ctx.fillStyle=gr;ctx.fillRect(gate[0],gate[1],gate[2],gate[3]);ctx.strokeStyle='#4d5c35';ctx.lineWidth=3;ctx.strokeRect(gate[0]+2,gate[1]+2,gate[2]-4,gate[3]-4)}for(const plate of l.b||[]){const active=g.opened.has(plate[2]),c=active?'#8dff87':plate[2]==='upperLift'?'#e43cff':'#ffd632';ctx.fillStyle=c;glow(c,11);ctx.beginPath();ctx.roundRect(plate[0],plate[1]-7,38,9,5);ctx.fill();resetGlow()}for(const gem of g.gems)if(!gem.taken){const c=gem.type==='fire'?'#ff281d':'#3cdcff';ctx.save();ctx.translate(gem.x+10,gem.y+14);glow(c,17);ctx.fillStyle=c;ctx.strokeStyle='#151b16';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-10,-5);ctx.lineTo(-4,-13);ctx.lineTo(6,-13);ctx.lineTo(11,-5);ctx.lineTo(0,13);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();resetGlow()}for(const v of l.d||[]){const d={x:v[0],y:v[1],type:v[2]},c=d.type==='fire'?'#ff291e':'#40d8ff';ctx.fillStyle='#625d46';ctx.fillRect(d.x-4,d.y-5,44,64);ctx.fillStyle='#252518';ctx.fillRect(d.x,d.y,36,59);ctx.strokeStyle=c;ctx.lineWidth=4;glow(c,13);ctx.strokeRect(d.x+3,d.y+3,30,53);ctx.fillStyle=c;ctx.font='900 29px sans-serif';ctx.textAlign='center';ctx.fillText(d.type==='fire'?'♂':'♀',d.x+18,d.y+39);resetGlow()}ctx.textAlign='left';for(const p of g.particles){ctx.globalAlpha=1-p.t/.7;ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,3,3)}ctx.globalAlpha=1;for(const a of g.actors)drawActor(a);ctx.fillStyle='#ffe56c';ctx.strokeStyle='#15200d';ctx.lineWidth=4;ctx.font='900 16px Georgia,serif';ctx.strokeText(L(l.n[0],l.n[1]),18,25);ctx.fillText(L(l.n[0],l.n[1]),18,25);ctx.textAlign='right';ctx.strokeText(L('🔥 方向键    💧 字母键','🔥 Arrow keys    💧 W/A/D'),882,25);ctx.fillText(L('🔥 方向键    💧 字母键','🔥 Arrow keys    💧 W/A/D'),882,25);ctx.textAlign='left';if(g.complete>0){ctx.fillStyle='#000a';ctx.fillRect(0,0,900,690);ctx.fillStyle='#f6df72';ctx.font='900 38px Georgia,serif';ctx.textAlign='center';ctx.fillText(L('神殿之门开启','TEMPLE CLEARED'),450,340);ctx.textAlign='left'}};
  load();setScore(0);return g;
}
