function initIronSnout(){
  canvas.width=900;canvas.height=540;canvas.className='iron-snout';controls([['←','left'],['↑','up'],['↓','down'],['→','right']]);
  const ground=442,heroX=450;
  const g={score:0,health:12,maxHealth:12,combo:0,comboTime:0,time:0,spawn:1.15,enemies:[],projectiles:[],particles:[],popups:[],pose:'',actionTime:0,facing:1,invuln:0,shake:0,kills:0};
  const nearestSide=()=>{const live=g.enemies.filter(e=>!e.dead).sort((a,b)=>Math.abs(a.x-heroX)-Math.abs(b.x-heroX))[0];return live?(live.x<heroX?-1:1):g.facing};
  const burst=(x,y,color,count=10)=>{for(let i=0;i<count;i++)g.particles.push({x,y,vx:(Math.random()-.5)*220,vy:-40-Math.random()*190,t:0,life:.35+Math.random()*.35,color,r:2+Math.random()*4})};
  const popup=(x,y,text,color='#fff')=>g.popups.push({x,y,text,color,t:0});
  const award=(base,x,y)=>{g.combo++;g.comboTime=2.4;const points=base+Math.min(30,g.combo)*8;g.score+=points;setScore(g.score);popup(x,y,`+${points}`,g.combo>8?'#ffe56c':'#fff')};
  const hitEnemy=(e,damage,dir,power=1)=>{if(e.dead||e.hit>0)return;e.hp-=damage;e.hit=.15;e.knock=dir*(135+power*80);burst(e.x,e.y-38,'#ffd36a',8);award(55,e.x,e.y-78);if(e.hp<=0){e.dead=true;e.deadTime=.65;g.kills++;e.knock=dir*(260+power*100);e.vy=-150-power*65;g.score+=100+e.maxHp*40;setScore(g.score);popup(e.x,e.y-105,L('击倒！','K.O.!'),'#ffcf45')}};
  const catchProjectile=(p,dir)=>{p.vx=dir*(360+Math.min(g.combo,20)*8);p.owner='hero';p.spin*=1.4;p.y-=8;burst(p.x,p.y,'#9dfcff',7);award(80,p.x,p.y-20)};
  const attack=(kind)=>{
    if(ended||g.actionTime>.09)return;let dir=g.facing;if(kind==='left')dir=-1;if(kind==='right')dir=1;if(kind==='up'||kind==='down')dir=nearestSide();g.facing=dir;g.pose=kind;g.actionTime=kind==='up'?.34:kind==='down'?.29:.23;
    const reach=kind==='up'?108:kind==='down'?130:122,power=kind==='up'?1.45:kind==='down'?1.2:1;
    for(const e of g.enemies){const dx=e.x-heroX,same=kind==='up'?Math.abs(dx)<reach:Math.sign(dx||dir)===dir&&Math.abs(dx)<reach;if(same&&!e.dead)hitEnemy(e,kind==='up'&&Math.abs(dx)<72?2:1,dir,power)}
    for(const p of g.projectiles)if(p.owner==='enemy'&&Math.abs(p.x-heroX)<reach&&(kind==='up'||Math.sign(p.x-heroX)===dir))catchProjectile(p,dir);
  };
  g.action=(kind,on)=>{if(on)attack(kind)};
  g.key=(key,on)=>{if(!on)return;const map={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down'};if(map[key])attack(map[key])};
  const spawnEnemy=()=>{
    const side=Math.random()<.5?-1:1,roll=Math.random(),unlocked=g.time>8,type=g.time>22&&roll<.18?'thrower':g.time>14&&roll<.4?'brute':unlocked&&roll<.65?'runner':'scout';
    const spec={scout:[1,82,'#626c78'],runner:[1,122,'#bb4454'],brute:[3,53,'#37435a'],thrower:[2,62,'#7e4ba5']}[type];
    g.enemies.push({type,side,x:side<0?-55:955,y:ground,hp:spec[0],maxHp:spec[0],speed:spec[1]*(1+Math.min(.45,g.time/140)),color:spec[2],hit:0,knock:0,vy:0,dead:false,deadTime:0,state:'walk',timer:0,throwCd:.8+Math.random()*.8,step:Math.random()*6});
  };
  const hurtHero=()=>{if(g.invuln>0||ended)return;g.health--;g.invuln=.85;g.shake=.28;g.combo=0;g.comboTime=0;burst(heroX,ground-58,'#ff5b64',18);popup(heroX,ground-120,L('受击！','HIT!'),'#ff6677');if(g.health<=0)finish(L('铁拳小猪倒下了','Iron Fist Pig was overwhelmed'))};
  const updateEnemy=(e,dt)=>{
    e.step+=dt*(e.type==='runner'?12:7);e.hit=Math.max(0,e.hit-dt);e.throwCd-=dt;
    if(e.dead){e.deadTime-=dt;e.x+=e.knock*dt;e.y+=e.vy*dt;e.vy+=520*dt;return}
    if(e.hit>0){e.x+=e.knock*dt;e.knock*=Math.pow(.05,dt);return}
    const dx=heroX-e.x,dist=Math.abs(dx),dir=Math.sign(dx),stop=e.type==='thrower'?195:60;
    if(e.state==='windup'){e.timer-=dt;if(e.timer<=0){if(Math.abs(heroX-e.x)<82)hurtHero();e.state='recover';e.timer=.42}return}
    if(e.state==='recover'){e.timer-=dt;if(e.timer<=0)e.state='walk';return}
    if(e.type==='thrower'&&dist<=215){if(e.throwCd<=0){g.projectiles.push({x:e.x+dir*24,y:ground-72,vx:dir*(235+Math.min(90,g.time*2)),owner:'enemy',spin:dir*7,angle:0});e.throwCd=1.35+Math.random()*.7;e.state='recover';e.timer=.24}return}
    if(dist>stop)e.x+=dir*e.speed*dt;else{e.state='windup';e.timer=e.type==='runner'?.25:e.type==='brute'?.62:.42}
  };
  g.update=dt=>{
    g.time+=dt;g.actionTime=Math.max(0,g.actionTime-dt);if(!g.actionTime)g.pose='';g.invuln=Math.max(0,g.invuln-dt);g.shake=Math.max(0,g.shake-dt);g.comboTime=Math.max(0,g.comboTime-dt);if(!g.comboTime)g.combo=0;
    g.spawn-=dt;if(g.spawn<=0){spawnEnemy();if(g.time>35&&Math.random()<.28)spawnEnemy();g.spawn=Math.max(.38,1.3-g.time*.012)*(0.82+Math.random()*.38)}
    g.enemies.forEach(e=>updateEnemy(e,dt));g.enemies=g.enemies.filter(e=>!e.dead||e.deadTime>0);
    for(const p of g.projectiles){p.x+=p.vx*dt;p.angle+=p.spin*dt;if(p.owner==='enemy'&&Math.abs(p.x-heroX)<24&&p.y>ground-115){p.owner='spent';hurtHero()}else if(p.owner==='hero'){for(const e of g.enemies)if(!e.dead&&Math.abs(e.x-p.x)<28){hitEnemy(e,2,Math.sign(p.vx),1.7);p.owner='spent';break}}}g.projectiles=g.projectiles.filter(p=>p.owner!=='spent'&&p.x>-80&&p.x<980);
    for(const p of g.particles){p.t+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=390*dt}g.particles=g.particles.filter(p=>p.t<p.life);for(const p of g.popups){p.t+=dt;p.y-=32*dt}g.popups=g.popups.filter(p=>p.t<.8);
    const wave=1+Math.floor(g.time/18);setStatus(L(`第 ${wave} 波 · 击倒 ${g.kills} · 连击 ${g.combo}`,`Wave ${wave} · ${g.kills} KOs · Combo ${g.combo}`));
  };
  const round=(x,y,w,h,r,fill)=>{ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill)ctx.fill();else ctx.stroke()};
  const drawBackground=()=>{const sky=ctx.createLinearGradient(0,0,0,ground);sky.addColorStop(0,'#bfe7e2');sky.addColorStop(.62,'#e8f1cf');sky.addColorStop(1,'#a5c06b');ctx.fillStyle=sky;ctx.fillRect(0,0,900,540);ctx.fillStyle='#98b6ae';ctx.beginPath();ctx.moveTo(0,230);for(let x=0;x<=900;x+=90)ctx.lineTo(x,145+Math.sin(x*.018)*38);ctx.lineTo(900,ground);ctx.lineTo(0,ground);ctx.fill();ctx.fillStyle='#56775b';for(let x=-30;x<960;x+=72){ctx.beginPath();ctx.arc(x,330+Math.sin(x)*8,75,0,7);ctx.fill()}ctx.fillStyle='#76965a';for(let x=-20;x<940;x+=55){ctx.beginPath();ctx.arc(x,365+(x%3)*7,48,0,7);ctx.fill()}const dirt=ctx.createLinearGradient(0,ground-10,0,540);dirt.addColorStop(0,'#b98859');dirt.addColorStop(1,'#6d4331');ctx.fillStyle=dirt;ctx.fillRect(0,ground-8,900,108);ctx.fillStyle='#d2ad72';ctx.fillRect(0,ground-8,900,9);ctx.fillStyle='#ffffff22';for(let i=0;i<14;i++)ctx.fillRect((i*83+27)%900,ground+22+(i%3)*17,18,3)};
  const drawHero=()=>{const a=g.pose,t=g.actionTime,dir=g.facing,bob=Math.sin(g.time*6)*2,jump=a==='up'?Math.sin(Math.min(1,(.34-t)/.34)*Math.PI)*34:0,duck=a==='down'?15:0;ctx.save();ctx.translate(heroX,ground-62+jump+duck);if(g.invuln>0&&Math.floor(g.invuln*12)%2)ctx.globalAlpha=.35;ctx.scale(dir,1);ctx.strokeStyle='#512c2c';ctx.lineWidth=6;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-12,22);ctx.lineTo(-22,47-bob);ctx.moveTo(10,22);ctx.lineTo(22,47+bob);ctx.stroke();const kick=a==='left'||a==='right'?38:a==='up'?55:a==='down'?52:22;ctx.beginPath();ctx.moveTo(8,15);ctx.lineTo(kick,20+(a==='up'?-20:a==='down'?18:0));ctx.stroke();ctx.fillStyle='#ef766b';ctx.beginPath();ctx.ellipse(0,2,28,34,0,0,7);ctx.fill();ctx.fillStyle='#f49b8f';ctx.beginPath();ctx.arc(0,-30,25,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(-16,-48);ctx.lineTo(-10,-67);ctx.lineTo(-2,-49);ctx.moveTo(13,-48);ctx.lineTo(20,-65);ctx.lineTo(22,-45);ctx.fill();ctx.fillStyle='#ffd1c1';ctx.beginPath();ctx.ellipse(17,-27,20,13,0,0,7);ctx.fill();ctx.fillStyle='#7e403d';ctx.beginPath();ctx.arc(12,-29,2.6,0,7);ctx.arc(22,-29,2.6,0,7);ctx.fill();ctx.fillStyle='#2b2530';ctx.beginPath();ctx.arc(9,-40,3.5,0,7);ctx.fill();ctx.strokeStyle='#f8d59a';ctx.lineWidth=5;const punch=a==='left'||a==='right'?58:a==='up'?40:28;ctx.beginPath();ctx.moveTo(12,-6);ctx.lineTo(punch,a==='up'?-38:-9);ctx.stroke();ctx.fillStyle='#fff0c3';ctx.beginPath();ctx.arc(punch,a==='up'?-38:-9,8,0,7);ctx.fill();ctx.restore()};
  const drawEnemy=e=>{const dir=e.x<heroX?1:-1,wob=Math.sin(e.step)*4;ctx.save();ctx.translate(e.x,e.y-58);ctx.scale(dir,1);if(e.dead)ctx.rotate((1-e.deadTime/.65)*dir*1.1);if(e.hit>0)ctx.globalAlpha=.65;ctx.strokeStyle='#26242d';ctx.lineWidth=e.type==='brute'?9:6;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-12,20);ctx.lineTo(-19,52+wob);ctx.moveTo(10,20);ctx.lineTo(19,52-wob);ctx.stroke();ctx.fillStyle=e.color;ctx.beginPath();ctx.ellipse(0,2,e.type==='brute'?31:25,e.type==='brute'?38:32,0,0,7);ctx.fill();ctx.fillStyle='#6c7783';ctx.beginPath();ctx.moveTo(-20,-33);ctx.lineTo(-13,-60);ctx.lineTo(-3,-39);ctx.lineTo(11,-55);ctx.lineTo(18,-28);ctx.arc(0,-28,25,0,Math.PI,true);ctx.fill();ctx.fillStyle='#d8d1bb';ctx.beginPath();ctx.ellipse(20,-24,23,13,0,0,7);ctx.fill();ctx.fillStyle='#24232b';ctx.beginPath();ctx.arc(29,-25,4,0,7);ctx.arc(7,-36,3.5,0,7);ctx.fill();ctx.strokeStyle='#f2d59d';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(16,-15);ctx.lineTo(27,-10);ctx.moveTo(20,-15);ctx.lineTo(31,-11);ctx.stroke();if(e.type==='thrower'){ctx.fillStyle='#ded7c7';ctx.save();ctx.translate(5,-5);ctx.rotate(-.7);ctx.fillRect(0,-3,30,6);ctx.restore()}if(e.maxHp>1&&!e.dead){for(let i=0;i<e.maxHp;i++){ctx.fillStyle=i<e.hp?'#ffcc51':'#0005';ctx.fillRect(-18+i*13,-75,10,4)}}ctx.restore()};
  g.draw=()=>{ctx.save();if(g.shake>0)ctx.translate((Math.random()-.5)*10,(Math.random()-.5)*7);drawBackground();for(const p of g.projectiles){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.fillStyle=p.owner==='hero'?'#71edff':'#e8e1d3';ctx.fillRect(-17,-3,34,6);ctx.fillStyle='#6c412e';ctx.fillRect(-22,-4,10,8);ctx.restore()}g.enemies.forEach(drawEnemy);drawHero();for(const p of g.particles){ctx.globalAlpha=1-p.t/p.life;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill()}ctx.globalAlpha=1;for(const p of g.popups){ctx.globalAlpha=1-p.t/.8;ctx.fillStyle=p.color;ctx.font='900 18px sans-serif';ctx.textAlign='center';ctx.fillText(p.text,p.x,p.y)}ctx.globalAlpha=1;ctx.restore();ctx.textAlign='left';ctx.fillStyle='#3a2630';ctx.font='900 17px sans-serif';ctx.fillText(L('体力','HEALTH'),24,28);for(let i=0;i<g.maxHealth;i++){ctx.fillStyle=i<g.health?'#ff5968':'#532e38';round(24+i*22,38,17,10,5,true)}ctx.textAlign='center';if(g.combo>1){ctx.fillStyle='#fff5c4';ctx.strokeStyle='#452632';ctx.lineWidth=5;ctx.font=`900 ${Math.min(42,24+g.combo)}px sans-serif`;ctx.strokeText(`${g.combo} COMBO`,450,54);ctx.fillText(`${g.combo} COMBO`,450,54)}ctx.textAlign='right';ctx.fillStyle='#3a2630';ctx.font='900 19px sans-serif';ctx.fillText(L(`击倒 ${g.kills}`,`${g.kills} KOs`),876,30);ctx.textAlign='left'};
  setScore(0);setStatus(L('准备迎战','Ready to fight'));return g;
}
